/* REFERENCE_ONLY · D003 fixture. Gera a marcação que as funções Rust produzem
 * (shell::shell_with_window, wm::*, nye::surface/app/message/proposal/voice/
 * confirm_dialog) com dados de exemplo, e usa os textos de i18n/ui_nye.rs.
 * Visores: o artboard tem o tamanho pedido (vp) e as media queries dos CSS de
 * produção são reescritas para essa largura; o layout da aplicação Nye usa
 * container queries, que respondem à largura real da janela. O artboard é
 * reduzido para caber no ecrã de captura. Não é código de produção. */
(async () => {
  const qs = new URLSearchParams(location.search);
  const S = qs.get('state') || '';
  const LANG = qs.get('lang') || 'pt';
  const [VW, VH] = (qs.get('vp') || '924x540').split('x').map(Number);
  const ROOT = '../../implementation/apps/workspace/';

  // CSS de produção com as media queries do visor pedido
  for (const l of Array.from(document.querySelectorAll('link[rel="stylesheet"][href*="static/"]'))) {
    let css = await (await fetch(l.href)).text();
    css = css.replace(/@font-face\s*\{[^}]*\}/g, '');
    css = css.replace(/@media \(max-width: (\d+(?:\.\d+)?)px\)/g, (m, n) => '@media (max-width: ' + (VW <= Number(n) ? 99999 : 0) + 'px)');
    css = css.replace(/@media \(min-width: (\d+(?:\.\d+)?)px\)/g, (m, n) => '@media (min-width: ' + (VW >= Number(n) ? 0 : 99999) + 'px)');
    css = css.replace(/@media \(hover: hover\) and \(min-width: (\d+)px\)/g, (m, n) => '@media (hover: hover) and (min-width: ' + (VW >= Number(n) ? 0 : 99999) + 'px)');
    const st = document.createElement('style'); st.textContent = css; l.replaceWith(st);
  }
  const svg = await (await fetch(ROOT + 'static/icons.svg')).text();
  const holder = document.createElement('div'); holder.hidden = true; holder.innerHTML = svg; document.body.prepend(holder);

  // textos: o catálogo real
  const cat = await (await fetch(ROOT + 'src/i18n/ui_nye.rs')).text();
  const T = {};
  const re = /"([^"]+)":\s*\{\s*pt:\s*"((?:[^"\\]|\\.)*)",\s*en:\s*"((?:[^"\\]|\\.)*)",\s*fr:\s*"((?:[^"\\]|\\.)*)"/g;
  let m; while ((m = re.exec(cat))) T[m[1]] = { pt: m[2], en: m[3], fr: m[4] };
  const t = (k, v) => { let s = (T[k] && T[k][LANG]) || ('⟦' + k + '⟧'); if (v) for (const [a, b] of Object.entries(v)) s = s.split('{' + a + '}').join(b); return s; };
  const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  const ic = (n) => `<svg class="oc-icon" aria-hidden="true" focusable="false"><use href="#${n}"></use></svg>`;
  const SH = { close: { pt: 'Fechar', en: 'Close', fr: 'Fermer' }[LANG] };

  // ── vocabulário (igual a nye/mod.rs) ──
  const KI = { app: 'apps', file: 'files', folder: 'folder', note: 'notes', project: 'project', task: 'tasks', member: 'user', setting: 'settings', action: 'command', dataset: 'data', mail: 'mail', event: 'calendar', conversation: 'nye', web: 'ob-globe', other: 'link' };
  const GK = { app: 'app', file: 'file', folder: 'file', note: 'note', project: 'project', task: 'task', member: 'member', setting: 'setting', action: 'action', dataset: 'dataset', mail: 'mail', event: 'event', conversation: 'conversation', web: 'other', other: 'other' };
  const RISK = { read_only: ['eye', 'read_only'], navigation: ['arrow-r', 'navigation'], reversible_write: ['edit', 'reversible_write'], institutional: ['organization', 'institutional'], external: ['send', 'external'], privileged: ['key', 'privileged'], destructive: ['trash', 'destructive'] };
  const EX = { proposed: 'clock', awaiting: 'clock', authorized: 'clock', running: 'refresh', completed: 'check', partial: 'warning', failed: 'warning', cancelled: 'close', blocked: 'lock', rejected: 'close', expired: 'close' };
  const risk = (r) => `<span class="oc-nye-risk" data-risk="${r}">${ic(RISK[r][0])}${t('nye.risk.' + RISK[r][1])}</span>`;
  const exec = (s) => `<span class="oc-nye-exec" data-state="${s}">${ic(EX[s])}${t('nye.exec.' + s)}</span>`;
  const STEP = { queued: ['clock'], running: ['refresh'], waiting: ['clock'], done: ['check'], failed: ['warning'], skipped: ['close'], awaiting: ['lock'] };

  const steps = (list) => `<ol class="oc-nye-steps">${list.map(([dom, label, st, det]) => `<li class="oc-nye-step" data-state="${st}"><span class="oc-nye-step__mark" aria-hidden="true">${ic(STEP[st][0])}</span><span class="oc-nye-step__text"><span class="oc-nye-step__label">${dom ? `<span class="oc-nye-step__domain">${dom}</span>` : ''}${label}</span>${det ? `<span class="oc-nye-step__detail">${det}</span>` : ''}</span><span class="oc-nye-step__state">${t('nye.step.' + st)}</span></li>`).join('')}</ol>`;
  const acts = (list, open) => {
    if (!list.length) return '';
    const doms = [...new Set(list.map((s) => s[0]).filter(Boolean))];
    const run = list.find((s) => s[2] === 'running' || s[2] === 'waiting');
    const sum = run ? (run[0] ? t('nye.activity.working', { domain: run[0] }) : run[1]) : t('nye.activity.count', { n: list.length });
    return `<details class="oc-nye-acts" ${open ? 'open' : ''}><summary class="oc-nye-acts__sum">${ic('activity')}<span>${sum}</span>${doms.length ? `<span class="oc-nye-acts__domains">${doms.join(' · ')}</span>` : ''}${ic('chev-d')}</summary>${steps(list)}</details>`;
  };
  const srcs = (list) => {
    const ext = list.some((s) => s.ext && s.ok !== false);
    return `<ol class="oc-nye-srcs">${list.map((s) => s.ok === false
      ? `<li class="oc-nye-src" data-available="false"><span class="oc-nye-src__n">${s.n}</span><span class="oc-nye-src__icon" aria-hidden="true">${ic('lock')}</span><span class="oc-nye-src__text"><span class="oc-nye-src__title">${t('nye.sources.unavailable')}</span></span></li>`
      : `<li class="oc-nye-src" data-trust="${s.ext ? 'external' : 'ocinye'}"><a class="oc-nye-src__link" href="#"><span class="oc-nye-src__n">${s.n}</span><span class="oc-nye-src__icon" aria-hidden="true">${ic(KI[s.k])}</span><span class="oc-nye-src__text"><span class="oc-nye-src__title">${s.title}</span><span class="oc-nye-src__meta">${[t('nye.kind.' + s.k), s.ctx, s.loc, s.at].filter(Boolean).join(' · ')}</span>${s.ext ? `<span class="oc-nye-src__trust">${ic('warning')}${t('nye.sources.external')}</span>` : ''}</span><span class="oc-sr">${t('nye.sources.open')}</span></a></li>`).join('')}</ol>${ext ? `<p class="oc-nye-note" data-tone="trust">${ic('shield')}<span>${t('nye.sources.external_note')}</span></p>` : ''}`;
  };
  const hitRow = (h) => `<li><a class="oc-nye-hit" href="#" data-part="nye-hit"><span class="oc-nye-hit__icon" aria-hidden="true">${ic(KI[h.k])}</span><span class="oc-nye-hit__text"><span class="oc-nye-hit__title">${h.title}</span><span class="oc-nye-hit__meta"><span class="oc-sr">${t('nye.kind.' + h.k)} · </span>${[h.ctx, h.meta].filter(Boolean).join(' · ')}</span></span>${h.app ? `<span class="oc-nye-hit__app">${h.app}</span>` : ''}</a></li>`;
  const groups = (gs) => gs.map(([k, hs]) => `<li class="oc-nye-group"><p class="oc-nye-group__title">${t('nye.group.' + GK[k])}</p><ul class="oc-nye-hits">${hs.map((h) => hitRow({ k, ...h })).join('')}</ul></li>`).join('');
  const kv = (label, value, long) => `<div class="oc-nye-kv" ${long ? 'data-long=""' : ''}><dt>${label}</dt><dd>${value}</dd></div>`;

  const proposal = (p) => {
    const decidable = p.auth === 'confirmation_required' && p.state === 'awaiting' && !p.superseded;
    const blocked = ['denied', 'unavailable', 'policy_blocked'].includes(p.auth);
    const strong = ['external', 'privileged', 'destructive'].includes(p.risk);
    return `<section class="oc-nye-prop" data-risk="${p.risk}" data-state="${p.state}" ${p.superseded ? 'data-superseded=""' : ''}>
      <header class="oc-nye-prop__head"><span class="oc-nye-prop__kicker">${t('nye.prop.kicker')}</span>${risk(p.risk)}<span class="oc-nye-prop__spacer"></span><span role="status">${exec(p.state)}</span></header>
      <h3 class="oc-nye-prop__title">${p.title}</h3>
      <dl class="oc-nye-prop__fields">${kv(t('nye.prop.target'), p.target)}${p.scope ? kv(t('nye.prop.scope'), p.scope) : ''}${(p.fields || []).map((f) => kv(f[0], f[1], f[2])).join('')}</dl>
      ${p.lines ? `<ul class="oc-nye-lines">${p.lines.map((l) => `<li class="oc-nye-line" ${l.ok === true ? 'data-ok="ok"' : l.ok === false ? 'data-ok="failed"' : ''}><${l.href ? 'a href="#"' : 'span'}><span class="oc-nye-line__mark" aria-hidden="true">${ic(l.ok === true ? 'check' : l.ok === false ? 'warning' : 'chev-r')}</span><span class="oc-nye-line__title">${l.title}</span>${l.meta ? `<span class="oc-nye-line__meta">${l.meta}</span>` : ''}</${l.href ? 'a' : 'span'}></li>`).join('')}</ul>` : ''}
      ${p.cons ? `<div class="oc-nye-prop__cons"><p class="oc-nye-prop__label">${t('nye.prop.consequences')}</p><ul>${p.cons.map((c) => `<li>${c}</li>`).join('')}</ul></div>` : ''}
      <p class="oc-nye-prop__auth" data-auth="${blocked ? 'blocked' : 'ok'}">${ic(blocked ? 'lock' : 'shield')}<span>${t('nye.auth.' + p.auth)}${p.auth === 'authorized' && p.state === 'proposed' ? ' · ' + t('nye.prop.no_confirm') : ''}</span></p>
      ${p.ext ? `<p class="oc-nye-note" data-tone="trust">${ic('shield')}<span>${t('nye.prop.external_origin')}</span></p>` : ''}
      ${p.superseded ? `<p class="oc-nye-note">${ic('refresh')}<span>${t('nye.prop.superseded')}</span></p>` : ''}
      ${p.exec ? `<div class="oc-nye-prop__exec">${p.exec.summary ? `<p class="oc-nye-prop__summary">${p.exec.summary}</p>` : ''}${p.exec.error ? `<p class="oc-state oc-state--error" role="alert">${ic('warning')}<span>${t('nye.reason.' + p.exec.error)}${p.exec.detail ? ' ' + p.exec.detail : ''}</span></p>` : ''}</div>` : ''}
      ${decidable ? `<div class="oc-nye-prop__actions"><form method="post" action="#"><button type="submit" class="oc-nye-btn">${t('nye.prop.cancel')}</button></form>${p.edit ? `<a class="oc-nye-btn" href="#" title="${esc(t('nye.prop.edit_note'))}">${ic('edit')}${t('nye.prop.edit')}</a>` : ''}<span class="oc-nye-prop__spacer"></span>${strong ? `<a class="oc-btn-gold" href="#" data-oc="nye-review">${t('nye.prop.review')}</a>` : `<form method="post" action="#"><input type="hidden" name="digest" value="d"><button type="submit" class="oc-btn-gold">${ic('check')}${t('nye.prop.confirm')}</button></form>`}</div>` : ''}
      ${p.exec && p.exec.retry ? `<form class="oc-nye-prop__actions" method="post" action="#"><button type="submit" class="oc-nye-btn">${ic('refresh')}${t('nye.exec.retry')}</button></form>` : ''}
      <details class="oc-nye-prop__details" ${p.details ? 'open' : ''}><summary>${t('nye.prop.details')}${ic('chev-d')}</summary><dl class="oc-nye-prop__fields oc-nye-prop__fields--mono">${kv(t('nye.prop.capability'), p.cap)}${p.exec && p.exec.audit ? kv(t('nye.prop.audit'), p.exec.audit) : ''}${p.exec && p.exec.at ? kv(t('nye.prop.at'), p.exec.at) : ''}${p.expires ? kv(t('nye.prop.expires'), p.expires) : ''}</dl></details>
    </section>`;
  };
  const confirmDlg = (p) => `<div class="oc-overlay oc-overlay--center" data-open="" data-oc="nye-confirm" role="alertdialog" aria-modal="true" aria-labelledby="oc-nye-confirm-t"><form class="oc-dialog oc-nye-confirm" data-risk="${p.risk}"><header class="oc-nye-confirm__head">${risk(p.risk)}<a class="oc-round-btn oc-round-btn--sm" href="#" aria-label="${t('nye.prop.cancel')}">${ic('close')}</a></header><p class="oc-nye-confirm__q">${t('nye.confirm.title')}</p><h2 class="oc-dialog__title" id="oc-nye-confirm-t">${p.title}</h2><dl class="oc-nye-prop__fields">${kv(t('nye.prop.target'), p.target)}${p.scope ? kv(t('nye.prop.scope'), p.scope) : ''}${(p.fields || []).map((f) => kv(f[0], f[1], f[2])).join('')}</dl>${p.cons ? `<div class="oc-nye-prop__cons"><p class="oc-nye-prop__label">${t('nye.prop.consequences')}</p><ul>${p.cons.map((c) => `<li>${c}</li>`).join('')}</ul></div>` : ''}${p.risk === 'destructive' ? `<p class="oc-nye-note" data-tone="block">${ic('warning')}<span>${t('nye.confirm.irreversible')}</span></p>` : ''}<p class="oc-dialog__note">${t('nye.confirm.immutable')}${p.expires ? ' ' + t('nye.confirm.expires', { time: p.expires }) : ''}</p><div class="oc-dialog__actions"><button type="submit" class="oc-btn-plain" data-oc="nye-confirm-cancel">${t('nye.prop.cancel')}</button><span class="oc-dialog__spacer"></span><button type="submit" class="${p.risk === 'destructive' ? 'oc-btn-line oc-btn-line--danger' : 'oc-btn-gold'}" data-oc="nye-confirm-ok">${t('nye.prop.confirm')}</button></div></form></div>`;

  const block = (b) => {
    if (typeof b === 'string') return `<p>${b}</p>`;
    if (b.p) return `<p>${b.p}${(b.c || []).map((n) => `<sup class="oc-nye-cite"><span class="oc-sr">${t('nye.sources.ref')} </span>${n}</sup>`).join('')}</p>`;
    if (b.h) return `<h4>${b.h}</h4>`;
    if (b.ul) return `<ul>${b.ul.map((i) => `<li>${i}</li>`).join('')}</ul>`;
    if (b.ol) return `<ol>${b.ol.map((i) => `<li>${i}</li>`).join('')}</ol>`;
    if (b.table) return `<div class="oc-nye-table"><table><thead><tr>${b.table[0].map((h) => `<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${b.table.slice(1).map((r) => `<tr>${r.map((c) => `<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
    if (b.quote) return `<blockquote class="oc-nye-quote">${b.quote}<sup class="oc-nye-cite">${b.cite}</sup></blockquote>`;
    return '';
  };
  const msg = (mm, compact) => {
    const mine = mm.role === 'member';
    const st = mm.state || 'complete';
    return `<article class="oc-nye-msg" data-role="${mine ? 'member' : 'nye'}" data-state="${st}" ${compact ? 'data-compact=""' : ''}>
      <header class="oc-nye-msg__head">${mine ? '' : `<span class="oc-nye-mark" aria-hidden="true">${ic('nye')}</span>`}<strong class="oc-nye-msg__who">${t(mine ? 'nye.you' : 'nye.name')}</strong><time class="oc-nye-msg__at">${mm.at || '10:42'}</time>${mm.proc === 'local' ? `<span class="oc-nye-proc" data-state="local">${ic('shield')}${t('nye.proc.local')}</span>` : mm.proc === 'external' ? `<span class="oc-nye-proc" data-state="external">${ic('ob-ext')}${t('nye.proc.external')}</span>` : ''}</header>
      ${!mine && mm.steps ? acts(mm.steps, mm.stepsOpen) : ''}
      ${mm.atts ? `<ul class="oc-nye-atts">${mm.atts.map((a) => `<li class="oc-nye-att">${ic(KI[a.k])}<span class="oc-nye-att__name">${a.name}</span><span class="oc-nye-att__meta">${a.meta}</span></li>`).join('')}</ul>` : ''}
      ${(mm.blocks || []).length || st === 'streaming' ? `<div class="oc-nye-msg__body" ${st === 'streaming' ? 'data-oc="nye-stream" aria-busy="true"' : ''}>${(mm.blocks || []).map(block).join('')}${st === 'streaming' ? '<span class="oc-nye-caret" aria-hidden="true"></span>' : ''}</div>` : ''}
      ${mm.proc === 'blocked' ? `<p class="oc-nye-note" data-tone="block" role="status">${ic('lock')}<span>${t('nye.proc.blocked')}</span></p>` : ''}
      ${mm.proc === 'approval' ? `<div class="oc-nye-egress" role="group"><p class="oc-nye-egress__text">${ic('ob-ext')}<span>${t('nye.proc.approval')}</span></p><form class="oc-nye-egress__actions"><button type="submit" class="oc-nye-btn">${t('nye.proc.local_only')}</button><button type="submit" class="oc-nye-btn oc-nye-btn--line">${t('nye.proc.approve')}</button></form></div>` : ''}
      ${mm.grounding === 'none' ? `<p class="oc-nye-note" data-grounding="none">${ic('help')}<span>${t('nye.grounding.none')}</span></p>` : mm.grounding === 'revoked' ? `<p class="oc-nye-note" data-grounding="revoked">${ic('lock')}<span>${t('nye.grounding.revoked')}</span></p>` : ''}
      ${mm.hits ? `<p class="oc-nye-det">${ic('search')}${t('nye.results.deterministic')}</p><ul class="oc-nye-groups">${groups(mm.hits)}</ul>` : ''}
      ${mm.sources ? `<div class="oc-nye-msg__sources"><p class="oc-nye-msg__label">${t('nye.sources.count', { n: mm.sources.length })}</p>${srcs(mm.sources)}</div>` : ''}
      ${(mm.props || []).map(proposal).join('')}
      ${mm.fail ? `<p class="oc-state oc-state--error" role="alert">${ic('warning')}<span>${t('nye.reason.' + mm.fail)}</span></p>` : ''}
      ${st === 'interrupted' ? `<p class="oc-nye-note">${ic('close')}<span>${t('nye.msg.interrupted')}</span></p>` : ''}
      ${st === 'streaming' ? `<div class="oc-nye-msg__actions"><form><button type="submit" class="oc-nye-btn">${ic('stop')}${t('nye.msg.stop')}</button></form></div>` : mm.retry ? `<div class="oc-nye-msg__actions"><form><button type="submit" class="oc-nye-btn">${ic('refresh')}${t('nye.msg.retry')}</button></form></div>` : ''}
    </article>`;
  };

  const avail = (a) => a === 'noai' ? `<div class="oc-nye-avail" data-state="limited" role="status">${ic('ai')}<span><strong>${t('nye.avail.no_inference.title')}</strong> ${t('nye.avail.no_inference.body')}<span class="oc-nye-avail__why">${t('nye.reason.no_inference')}</span></span></div>`
    : a === 'down' ? `<div class="oc-nye-avail" data-state="down" role="alert">${ic('warning')}<span><strong>${t('nye.avail.core_down.title')}</strong> ${t('nye.avail.core_down.body')}</span></div>`
    : a === 'reconnect' ? `<div class="oc-nye-avail" data-state="warn" role="status">${ic('refresh')}<span>${t('nye.avail.reconnecting')}</span></div>` : '';
  const ctxChip = (c) => c ? `<span class="oc-nye-ctx" data-state="${c.state || 'active'}"><span class="oc-sr">${t('nye.ctx.label')}: </span>${ic('workspace')}<a class="oc-nye-ctx__btn" href="#" title="${esc(t('nye.ctx.change'))}"><span class="oc-nye-ctx__kind">${t('nye.ctx.kind.' + c.kind)}</span><span class="oc-nye-ctx__name">${c.state === 'unavailable' ? t('nye.ctx.unavailable_short') : c.label}</span>${c.parent && c.state !== 'unavailable' ? `<span class="oc-nye-ctx__parent">${c.parent}</span>` : ''}${ic('chev-d')}</a></span>` : '';
  const chip = (ai, voice) => `<span class="oc-nye-chip" role="group" aria-label="${t('nye.status.label')}">${[[true, 'search'], [ai, 'answers'], [voice, 'voice']].map(([ok, k]) => `<span class="oc-nye-chip__part" data-state="${ok ? 'ok' : 'off'}"><span class="oc-nye-chip__dot" aria-hidden="true"></span>${t('nye.status.' + k)}<span class="oc-sr"> · ${t(ok ? 'nye.status.on' : 'nye.status.off')}</span></span>`).join('')}</span>`;
  const SOL = { kind: 'project', label: 'Projeto Solander', parent: 'Unidade de Investigação' };

  const APPS = [['Ficheiros', '/files', 'files'], ['Notas', '/notes', 'notes'], ['Projectos', '/projects', 'project'], ['Tarefas', '/tasks', 'tasks'], ['Calendário', '/calendar', 'calendar'], ['Correio', '/mail', 'mail'], ['Datasets', '/datasets', 'data'], ['Terminal', '/terminal', 'terminal']];
  const surface = (o) => {
    const ai = o.ai !== false;
    const mode = (v, k, dis) => `<label class="oc-nye-mode" title="${esc(t('nye.intent.hint.' + (v || 'auto')))}"><input type="radio" name="intent" value="${v}" data-part="nye-intent" ${(o.intent || '') === v ? 'checked' : ''} ${dis ? 'disabled' : ''}><span>${t(k)}</span>${dis ? `<span class="oc-sr">${t('nye.reason.no_inference')}</span>` : ''}</label>`;
    const ph = o.intent ? 'nye.placeholder.' + o.intent : 'nye.placeholder.auto';
    const q = o.q || '';
    const apps = APPS.filter(([n]) => !q || n.toLowerCase().includes(q.toLowerCase()));
    return `<div class="oc-overlay" id="oc-palette" data-oc="palette" data-nye="" data-open="" role="dialog" aria-modal="true" aria-labelledby="oc-nye-title"><a class="oc-overlay__scrim" href="#" aria-label="${SH.close}"></a>
      <form class="oc-palette oc-nyeu" method="get" action="#" role="search" data-oc="nye-surface" data-intent="${o.intent || 'auto'}"><h2 class="oc-sr" id="oc-nye-title">${t('nye.surface.label')}</h2>
        <div class="oc-nyeu__head"><label class="oc-field oc-field--lg oc-nyeu__field"><span class="oc-sr">${t('nye.surface.label')}</span><span class="oc-nye-mark" aria-hidden="true">${ic('nye')}</span><input name="q" type="search" data-part="palette-q" value="${esc(q)}" placeholder="${esc(t(ph))}" autocomplete="off"></label><button type="submit" class="oc-nyeu__go" aria-label="${t('nye.submit')}">${ic('arrow-r')}</button></div>
        <div class="oc-nyeu__bar"><fieldset class="oc-nye-modes"><legend class="oc-sr">${t('nye.intent.legend')}</legend>${mode('', 'nye.intent.auto')}${mode('search', 'nye.intent.search')}${mode('ask', 'nye.intent.ask', !ai)}${mode('act', 'nye.intent.act', !ai)}</fieldset>${ctxChip(o.ctx)}</div>
        ${avail(o.avail || (ai ? '' : 'noai'))}
        ${o.detected ? `<p class="oc-nye-read" role="status">${t('nye.intent.detected', { intent: t('nye.intent.' + o.detected) })}</p>` : ''}
        <div class="oc-nyeu__body" data-part="nye-results">
          ${o.answer ? msg(o.answer, true) : ''}
          ${o.hits ? `<p class="oc-nye-det">${ic('search')}${t('nye.results.deterministic')}</p>` : ''}
          <ul class="oc-nye-groups">${o.hits ? groups(o.hits) : ''}${apps.length && !o.noApps ? `<li class="oc-nye-group" data-part="nye-apps"><p class="oc-nye-group__title">${t('nye.group.app')}</p><ul class="oc-palette__list oc-nye-hits">${apps.map(([n, h, i]) => `<li data-part="palette-item" data-search="${n.toLowerCase()}"><a class="oc-nye-hit" href="#" data-part="nye-hit"><span class="oc-nye-hit__icon" aria-hidden="true">${ic(i)}</span><span class="oc-nye-hit__text"><span class="oc-nye-hit__title">${n}</span></span><span class="oc-nye-hit__app">${t('nye.kind.app')}</span></a></li>`).join('')}</ul></li>` : ''}</ul>
        </div>
        <p class="oc-palette__foot oc-nyeu__foot"><span class="oc-nyeu__keys">${t('nye.keys.hint')} · ${t('nye.shortcut', { keys: '⌘K' })}</span><a class="oc-nyeu__continue" href="#">${ic('nye')}${t('nye.open_in_nye')}</a></p>
      </form></div>`;
  };

  const composer = (o = {}) => `<form class="oc-nye-comp" data-oc="nye-composer" data-state="${o.state || 'idle'}">${o.atts ? `<ul class="oc-nye-atts">${o.atts.map((a) => `<li class="oc-nye-att">${ic(KI[a.k])}<span class="oc-nye-att__name">${a.name}</span><span class="oc-nye-att__meta">${a.meta}</span><button type="submit" class="oc-nye-att__x" aria-label="${esc(t('nye.comp.remove', { name: a.name }))}">${ic('close')}</button></li>`).join('')}</ul>` : ''}<label class="oc-sr" for="oc-nye-input">${t('nye.comp.label')}</label><textarea id="oc-nye-input" rows="1" data-part="nye-input" placeholder="${esc(t('nye.comp.placeholder'))}">${o.text || ''}</textarea><div class="oc-nye-comp__bar">${o.attach ? `<a class="oc-nye-icon-btn" href="#" aria-label="${t('nye.comp.attach')}">${ic('attach')}</a>` : `<button type="button" class="oc-nye-icon-btn" aria-disabled="true" aria-label="${t('nye.comp.attach')}" title="${esc(t('nye.comp.attach_na'))}">${ic('attach')}</button>`}${o.voice === false ? `<button type="button" class="oc-nye-icon-btn" aria-disabled="true" aria-label="${t('nye.comp.voice')}">${ic('mic')}</button>` : `<a class="oc-nye-icon-btn" href="#" aria-label="${t('nye.comp.voice')}">${ic('mic')}</a>`}<span class="oc-nye-comp__hint">${o.note ? t(o.note) : t('nye.comp.hint')}</span>${o.state === 'streaming' ? `<button type="submit" class="oc-nye-send" data-kind="stop" aria-label="${t('nye.comp.stop')}">${ic('stop')}</button>` : `<button type="submit" class="oc-nye-send" aria-label="${t('nye.comp.send')}">${ic('send')}</button>`}</div></form>`;
  const CONVS = [['Revisão semanal · Solander', 'hoje, 10:31'], ['Medições de vento — Namibe', 'hoje, 09:12'], ['Notas de investigação de setembro', 'ontem'], ['Plano de recolha do sensor 04', '26 set'], ['Resumo do relatório Q3', '22 set']];
  const rail = (o) => `<aside class="oc-nye__rail" id="oc-nye-rail" data-part="nye-drawer" ${o.railOpen ? 'data-open=""' : ''} aria-label="${t('nye.app.history')}"><div class="oc-nye__rail-head"><a class="oc-btn-gold oc-nye__new" href="#">${ic('plus')}${t('nye.app.new')}</a><button type="button" class="oc-nye-icon-btn oc-nye__drawer-x" data-oc="nye-drawer-close" aria-label="${t('nye.app.panel.close')}">${ic('close')}</button></div>${o.noHistory ? '' : `<form class="oc-nye-rail__search" role="search"><label class="oc-field"><span class="oc-sr">${t('nye.app.search_conv')}</span>${ic('search')}<input type="search" placeholder="${esc(t('nye.app.search_conv'))}"></label></form>`}<p class="oc-nye-rail__title">${t('nye.app.history')}</p>${o.noHistory ? `<p class="oc-pending oc-nye-rail__gap" role="status">${ic('clock')}<span>${t('nye.app.history_gap')}</span></p>` : `<ul class="oc-nye-convs">${CONVS.map(([n, a], i) => `<li><a class="oc-nye-conv" href="#" ${i === (o.convActive ?? 0) && !o.newConv ? 'aria-current="page"' : ''}><span class="oc-nye-conv__title">${n}</span><span class="oc-nye-conv__at">${a}</span></a></li>`).join('')}</ul>`}<p class="oc-nye-rail__note">${t('nye.app.history_note')}</p></aside>`;
  const side = (o) => !o.panel ? '' : `<aside class="oc-nye__side" id="oc-nye-side" data-part="nye-drawer" data-open=""><div class="oc-nye__side-head"><nav class="oc-nye-tabs" aria-label="${t('nye.app.panels')}"><a class="oc-nye-tab" href="#" ${o.panel === 'sources' ? 'aria-current="page"' : ''}>${t('nye.sources.title')}</a><a class="oc-nye-tab" href="#" ${o.panel === 'activity' ? 'aria-current="page"' : ''}>${t('nye.activity.title')}</a></nav><a class="oc-nye-icon-btn" href="#" aria-label="${t('nye.app.panel.close')}">${ic('close')}</a></div>${o.panel === 'sources' ? srcs(o.panelSources) : `<p class="oc-nye-side__note">${t('nye.activity.note')}</p>${steps(o.panelSteps)}`}</aside>`;
  const voice = (v) => {
    const listening = v.state === 'listening';
    const can = !['unavailable', 'error', 'requesting', 'transcribing', 'processing'].includes(v.state);
    return `<section class="oc-nye-voice" data-oc="nye-voice" data-state="${v.state}"><p class="oc-nye-voice__rec" ${listening ? 'data-on=""' : ''} role="status"><span class="oc-nye-voice__dot" aria-hidden="true"></span><span>${t('nye.voice.' + v.state)}</span></p>${v.why ? `<p class="oc-nye-voice__why">${t('nye.reason.' + v.why)}</p>` : ''}<button type="button" class="oc-nye-ptt" ${can ? 'data-oc="nye-ptt"' : 'aria-disabled="true"'} aria-pressed="${listening}"><span class="oc-nye-ptt__ring" aria-hidden="true">${ic(v.state === 'speaking' ? 'volume' : 'mic')}</span><span class="oc-nye-ptt__label">${t(listening ? 'nye.voice.stop_listening' : 'nye.voice.ptt')}</span></button><p class="oc-nye-voice__hint">${t('nye.voice.ptt_hold')}</p>${v.transcript ? `<blockquote class="oc-nye-voice__transcript">${v.transcript}</blockquote>` : ''}<div class="oc-nye-voice__controls">${v.state === 'speaking' ? `<button type="button" class="oc-nye-btn">${ic('stop')}${t('nye.voice.stop_speaking')}</button>` : ''}${v.replay ? `<button type="button" class="oc-nye-btn">${ic('volume')}${t('nye.voice.replay')}</button>` : ''}<label class="oc-nye-voice__lang"><span>${t('nye.voice.lang')}</span><select>${['pt', 'en', 'fr'].map((l) => `<option ${l === (v.lang || 'pt') ? 'selected' : ''}>${t('nye.voice.lang.' + l)}</option>`).join('')}</select></label>${v.detected ? `<span class="oc-nye-voice__det">${t('nye.voice.lang_detected')}</span>` : ''}<a class="oc-nye-btn" href="#">${ic('type')}${t('nye.voice.to_text')}</a></div><p class="oc-nye-voice__privacy">${ic('shield')}<span>${t('nye.voice.privacy')}</span></p></section>`;
  };
  const app = (o) => {
    const title = o.title || (o.messages ? CONVS[o.convActive ?? 0][0] : t('nye.app.new'));
    const ai = o.ai !== false;
    const body = o.voice ? voice(o.voice) : !o.messages ? `<div class="oc-nye-start"><span class="oc-nye-mark oc-nye-mark--lg" aria-hidden="true">${ic('nye')}</span><p class="oc-nye-start__title">${t('nye.app.empty.title')}</p><p class="oc-nye-start__body">${t('nye.app.empty.body')}</p><ul class="oc-nye-sugs">${['Encontrar ficheiros sobre medições de vento', 'Resumir as últimas notas de investigação', 'Preparar a revisão semanal do projecto', 'Abrir o último relatório Solander'].map((s) => `<li><a class="oc-nye-sug" href="#">${s}</a></li>`).join('')}</ul></div>` : `<div class="oc-nye-log">${o.messages.map((x) => msg(x, false)).join('')}</div>`;
    return `<div class="oc-nye" data-oc="nye-app" data-panel="${o.panel || 'none'}"><div class="oc-nye__grid">${rail(o)}<section class="oc-nye__main"><header class="oc-nye__bar"><button type="button" class="oc-nye-icon-btn oc-nye__rail-btn" data-oc="nye-drawer" aria-expanded="${!!o.railOpen}" aria-label="${t('nye.app.history')}">${ic('sidebar')}</button><h2 class="oc-nye__title">${title}</h2>${ctxChip(o.ctx === undefined ? SOL : o.ctx)}<span class="oc-nye-prop__spacer"></span>${chip(ai, o.voiceOk !== false && ai)}<a class="oc-nye-icon-btn" href="#" ${o.panel === 'sources' ? 'aria-current="page"' : ''} aria-label="${t('nye.sources.title')}">${ic('link')}</a><a class="oc-nye-icon-btn" href="#" ${o.panel === 'activity' ? 'aria-current="page"' : ''} aria-label="${t('nye.activity.title')}">${ic('activity')}</a></header>${avail(o.avail || (ai ? '' : 'noai'))}${o.ctxNote === 'changed' ? `<p class="oc-nye-note" role="status">${ic('workspace')}<span>${t('nye.ctx.changed', { ctx: 'Espaço Pessoal' })}</span></p>` : o.ctxNote === 'unavailable' ? `<p class="oc-nye-note" data-tone="warn" role="status">${ic('lock')}<span>${t('nye.ctx.unavailable')}</span></p>` : ''}<div class="oc-nye__scroll" data-part="nye-scroll">${body}</div><p class="oc-sr" role="status" data-part="nye-live"></p>${o.voice ? '' : composer(o.comp || { attach: true, voice: o.voiceOk !== false && ai, note: ai ? null : 'nye.comp.unavailable', state: ai ? 'idle' : 'unavailable' })}</section>${side(o)}</div></div>`;
  };

  // ── casca (igual a D002 fixture) ──
  const topbar = () => `<header class="oc-top"><details class="oc-menu"><summary class="oc-logo"><img src="${ROOT}static/ocinye-logo.png" alt="" width="44" height="44"></summary></details><details class="oc-menu"><summary class="oc-dist">Re</summary></details><form class="oc-nyebar" role="search">${ic('nye')}<input type="search" placeholder="Pergunte ou peça à Nye…"><button type="button" class="oc-nyebar__mic" aria-disabled="true">${ic('mic')}</button><kbd class="oc-kbd">⌘K</kbd></form><details class="oc-menu oc-create"><summary class="oc-create__btn">${ic('plus')}Criar</summary></details><details class="oc-menu oc-panel-menu"><summary class="oc-status"><span class="oc-status__part" data-state="ok"><span class="oc-status__dot"></span>CORE</span><span class="oc-status__part" data-state="${S.includes('noai') ? 'down' : 'ok'}"><span class="oc-status__dot"></span>IA</span></summary></details><details class="oc-menu oc-panel-menu"><summary class="oc-round-btn">${ic('bell')}<span class="oc-badge">2</span></summary></details><details class="oc-menu oc-panel-menu"><summary class="oc-clock-btn"><span class="oc-clock"><span data-part="clock-date">Ter 29 set</span><span data-part="clock-time">10:42</span></span></summary></details></header>`;
  const WA = { files: ['Ficheiros', 'files'], notes: ['Notas', 'notes'], nye: [t('nye.name'), 'nye'], terminal: ['Terminal', 'terminal'] };
  const dock = (ws) => `<nav class="oc-dock" data-oc="dock"><a class="oc-dock__btn" href="#">${ic('home')}</a><a class="oc-dock__btn oc-dock__brand" href="#">${ic('apps-brand-dark')}</a><span class="oc-dock__sep"></span>${(() => { const PIN = ['files', 'notes', 'terminal']; const extra = [...new Set(ws.map((w) => w.app))].filter((a) => !PIN.includes(a)); return [...PIN, ...(extra.length ? ['|'] : []), ...extra]; })().map((a) => { if (a === '|') return '<span class="oc-dock__sep" data-part="dock-running" aria-hidden="true"></span>'; const mine = ws.filter((w) => w.app === a); const act = mine.some((w) => w.active); return `<a class="oc-dock__btn" href="#" ${act ? 'aria-current="page"' : ''} ${mine.length ? `data-oc="dock-app" data-windows="1"` : ''}>${ic(WA[a][1])}${mine.length ? `<span class="oc-dock__run" data-n="1" ${act ? 'data-active=""' : ''}></span>` : ''}</a>`; }).join('')}</nav>`;
  const win = (w) => { const [title, icn] = WA[w.app]; const max = w.state === 'maximized'; return `<section class="oc-win" id="win-${w.id}" data-oc="win" data-win="${w.id}" data-app="${w.app}" data-state="${w.state || 'normal'}" ${w.active ? 'data-active=""' : ''} data-z="${w.z}" data-x="${w.x}" data-y="${w.y}" data-w="${w.w}" data-h="${w.h}"><header class="oc-win__bar" data-part="win-drag"><button type="submit" class="oc-win__back" data-oc="wm" data-op="minimize" aria-label="Voltar ao Desktop">${ic('chev-l')}</button><span class="oc-win__icon" aria-hidden="true">${ic(icn)}</span><span class="oc-win__names"><h2 class="oc-win__title">${title}</h2>${w.sub ? `<span class="oc-win__sub">${w.sub}</span>` : ''}</span><a class="oc-win__switch" href="#" aria-label="Alternar janelas">${ic('windows')}</a><form class="oc-win__controls"><button type="submit" class="oc-win__ctl" data-oc="wm" data-op="minimize" aria-label="Minimizar">${ic('win-min')}</button><button type="submit" class="oc-win__ctl" data-part="win-max" data-oc="wm" data-op="${max ? 'restore' : 'maximize'}" aria-label="Maximizar">${ic(max ? 'win-restore' : 'win-max')}</button><button type="submit" class="oc-win__ctl oc-win__ctl--close" data-oc="wm" data-op="close" aria-label="Fechar">${ic('close')}</button></form></header><div class="oc-win__body" data-part="win-body">${w.body || ''}</div>${['n', 'e', 's', 'w', 'ne', 'nw', 'se', 'sw'].map((e) => `<span class="oc-win__rz" data-part="win-resize" data-edge="${e}"></span>`).join('')}</section>`; };
  const shelf = (ws) => `<nav class="oc-shelf" data-oc="shelf" aria-label="Janelas abertas"><a class="oc-shelf__all" href="#">${ic('windows')}</a><ul class="oc-shelf__list">${ws.map((w) => `<li><a class="oc-shelf__item" href="#" data-state="${w.state || 'normal'}" ${w.active ? 'aria-current="true"' : ''}>${ic(WA[w.app][1])}<span class="oc-shelf__name">${w.sub || WA[w.app][0]}</span></a></li>`).join('')}</ul></nav>`;
  const FILES = `<div class="fx-files">${['Relatório Q3.pdf|2,4 MB|há 2 h', 'Medições de vento — Namibe.csv|12 MB|hoje', 'Plano de trabalho 2026.docx|320 KB|22/09', 'Sensor 04 — leituras.csv|12 MB|20/09'].map((r) => { const [a, b, c] = r.split('|'); return `<div class="fx-row">${ic('files')}<span>${a}</span><small>${b}</small><small>${c}</small></div>`; }).join('')}</div>`;

  // ── dados de exemplo ──
  const WIND = [['file', [{ title: 'Medições de vento — Namibe.csv', ctx: 'Projectos / Solander / Dados', meta: 'alterado há 2 h · 12 MB', app: 'Ficheiros' }, { title: 'Medições de vento — Namibe (2025).csv', ctx: 'Arquivo / Solander', meta: '14/11/2025 · 9,8 MB', app: 'Ficheiros' }, { title: 'Relatório de medições anemométricas.pdf', ctx: 'Projectos / Solander / Relatórios', meta: '22/09 · 2,1 MB', app: 'Ficheiros' }]], ['note', [{ title: 'Calibração do anemómetro · torre 2', ctx: 'Notas / Solander', meta: '26 set', app: 'Notas' }]], ['dataset', [{ title: 'Vento Namibe 10 min (2024–2026)', ctx: 'Datasets / Unidade de Investigação', meta: '3,1 M registos', app: 'Datasets' }]]];
  const S_NOTES = [{ n: 1, k: 'note', title: 'Notas de campo · 24 set', ctx: 'Notas / Solander', at: '24 set' }, { n: 2, k: 'note', title: 'Calibração do anemómetro · torre 2', ctx: 'Notas / Solander', at: '26 set' }, { n: 3, k: 'file', title: 'Relatório de medições anemométricas.pdf', ctx: 'Projectos / Solander / Relatórios', loc: 'p. 4', at: '22 set' }, { n: 4, k: 'task', title: 'Rever a série da torre 2', ctx: 'Tarefas / Solander', at: '27 set' }];
  const SUMMARY = [{ p: 'As notas da última semana tratam sobretudo da campanha de medição na torre 2 do Namibe.', c: [] }, { ul: ['A calibração do anemómetro da torre 2 foi refeita a 26 set; o desvio passou de 3,1 % para 0,4 %.', 'Há uma falha de 6 h na série de 24 set, entre as 02:00 e as 08:00, por corte de energia.', 'A revisão da série da torre 2 continua aberta e depende da nova calibração.'] }, { p: 'O relatório de 22 set indica uma velocidade média de 7,8 m/s a 80 m no período medido.', c: [3] }];
  const Q_ASK = { role: 'member', at: '10:40', blocks: ['Resume as últimas notas de investigação do projecto.'] };
  const A_ASK = { at: '10:41', proc: 'local', steps: [['Notas', 'Encontrou 6 notas dos últimos 7 dias', 'done'], ['Ficheiros', 'Leu 1 relatório', 'done'], [null, 'Preparou a resposta', 'done']], blocks: [{ p: SUMMARY[0].p, c: [1] }, { ul: SUMMARY[1].ul.map((x, i) => x + ['', '', ''][i]) }, { p: SUMMARY[2].p, c: [3] }], sources: S_NOTES };
  A_ASK.blocks[1] = { ul: ['A calibração do anemómetro da torre 2 foi refeita a 26 set; o desvio passou de 3,1 % para 0,4 %.', 'Há uma falha de 6 h na série de 24 set, entre as 02:00 e as 08:00, por corte de energia.', 'A revisão da série da torre 2 continua aberta e depende da nova calibração.'] };
  const TASKS = { risk: 'reversible_write', auth: 'confirmation_required', state: 'awaiting', title: 'Criar 3 tarefas no Projeto Solander', target: 'Projeto Solander', scope: 'Unidade de Investigação', cap: 'collaboration.task.create', edit: 1, expires: '10:57', lines: [{ title: 'Rever a série de 24 set (falha de 6 h)', meta: 'Ana Sebastião · 3 out' }, { title: 'Validar a calibração da torre 2', meta: 'Fidel Monteiro · 6 out' }, { title: 'Actualizar o relatório de medições', meta: 'sem responsável · 10 out' }], cons: ['As tarefas ficam visíveis a quem tem acesso ao Projeto Solander.', 'Os responsáveis recebem uma notificação.'] };
  const MAIL = { risk: 'external', auth: 'confirmation_required', state: 'awaiting', title: 'Enviar a revisão semanal a 52 destinatários', target: 'Lista «Parceiros Solander» · 52 destinatários', scope: 'Projeto Solander', cap: 'mail.message.send', expires: '10:57', fields: [['Assunto', 'Solander · revisão semanal · 29 set'], ['Anexos', 'Revisão semanal 29-09.pdf · 1,2 MB'], ['Mensagem', 'Caros parceiros,\n\nSegue a revisão semanal do Projeto Solander: calibração da torre 2 concluída, falha de 6 h na série de 24 set identificada e três tarefas abertas para a próxima semana.\n\nCumprimentos,\nFidel Monteiro', 1]], cons: ['A mensagem sai da instituição e não pode ser recolhida.', '41 dos 52 destinatários são externos à Instância.'] };
  const DEL = { risk: 'destructive', auth: 'confirmation_required', state: 'awaiting', title: 'Eliminar definitivamente o projecto «Piloto Huíla 2023»', target: 'Projeto «Piloto Huíla 2023»', scope: 'Unidade de Investigação', cap: '— (sem capacidade no Core: contrato de apresentação)', expires: '10:57', fields: [['Conteúdo', '214 ficheiros · 38 notas · 12 tarefas']], cons: ['O projecto e todo o seu conteúdo deixam de existir.', 'Os 9 membros perdem o acesso.', 'Os registos de auditoria mantêm-se.'] };
  const U_TASKS = { role: 'member', at: '10:44', blocks: ['Cria três tarefas para o Solander a partir destas notas.'] };
  const U_REVIEW = { role: 'member', at: '10:30', blocks: ['Prepara a revisão semanal do projecto.'] };
  const REVIEW_STEPS_RUN = [['Tarefas', 'Encontrou 7 tarefas abertas', 'done'], ['Notas', 'Encontrou 4 notas recentes', 'done'], ['Projectos', 'A resumir as alterações da semana', 'running'], [null, 'Preparar o rascunho da revisão', 'queued']];
  const REVIEW_STEPS = [['Tarefas', 'Encontrou 7 tarefas abertas', 'done'], ['Notas', 'Encontrou 4 notas recentes', 'done'], ['Projectos', 'Resumiu as alterações da semana', 'done'], ['Ficheiros', 'Criou o rascunho «Revisão semanal 29-09»', 'done', 'Ficheiros / Solander / Revisões'], ['Correio', 'Envio aos parceiros', 'awaiting', 'Nada é enviado sem a sua confirmação']];

  const W = (body, extra) => ({ app: 'nye', id: 'y1', sub: '', x: 40, y: 16, w: 1260, h: 760, z: 3, active: 1, body, ...extra });
  const desktopWins = (nyeBody, max) => [{ app: 'files', id: 'f1', sub: 'Projectos / Solander', x: 20, y: 20, w: 520, h: 330, z: 1, body: FILES }, W(nyeBody, max ? { state: 'maximized' } : VW < 1100 ? { state: 'maximized' } : {})];

  const STATES = {
    'surface-empty': { vp: '924x540', d: 'Superfície universal · vazia', surface: {} },
    'surface-empty-en': { vp: '924x540', lang: 'en', d: 'Universal surface · empty (en)', surface: {} },
    'surface-empty-fr': { vp: '924x540', lang: 'fr', d: 'Surface universelle · vide (fr)', surface: {} },
    'search-results': { vp: '1440x900', d: 'Pesquisa · medições de vento', surface: { q: 'medições de vento', detected: 'search', hits: WIND, noApps: 1 } },
    'ask-streaming': { vp: '924x540', d: 'Perguntar · resposta a chegar', surface: { q: 'Resume as últimas notas de investigação', intent: 'ask', ctx: SOL, noApps: 1, answer: { state: 'streaming', steps: [['Notas', 'Encontrou 6 notas dos últimos 7 dias', 'done'], [null, 'A preparar a resposta', 'running']], blocks: [{ p: SUMMARY[0].p, c: [1] }, 'A calibração do anemómetro da torre 2 foi refeita a 26 set; o desvio'] } } },
    'ask-sources': { vp: '924x540', d: 'Perguntar · resposta com fontes (app, tablet)', app: { messages: [Q_ASK, A_ASK] } },
    'no-inference': { vp: '924x540', d: 'Sem inferência · pesquisa continua', surface: { ai: false, q: 'vento', detected: 'search', hits: [WIND[0]], noApps: 1 } },
    'search-no-ai': { vp: '1440x900', d: 'Pesquisa determinística com IA indisponível (desktop)', surface: { ai: false, q: 'medições de vento', intent: 'search', hits: WIND, noApps: 1 } },
    'navigation': { vp: '924x540', d: 'Navegação · abrir o último relatório Solander', surface: { q: 'Abre o último relatório Solander', detected: 'act', noApps: 1, answer: { steps: [['Ficheiros', 'Encontrou «Relatório de medições anemométricas.pdf»', 'done']], blocks: [], props: [{ risk: 'navigation', auth: 'authorized', state: 'completed', title: 'Abrir «Relatório de medições anemométricas.pdf»', target: 'Projectos / Solander / Relatórios', cap: 'navigation.open', exec: { summary: 'Aberto em Ficheiros.' } }] } } },
    'proposal': { vp: '1440x900', d: 'Proposta de capacidade · criar 3 tarefas', app: { messages: [Q_ASK, { ...A_ASK, sources: undefined, steps: undefined, blocks: [A_ASK.blocks[0]] }, U_TASKS, { at: '10:44', steps: [['Projectos', 'Leu o Projeto Solander', 'done'], ['Tarefas', 'Preparou 3 tarefas', 'done']], blocks: ['Proponho estas três tarefas. Nada é criado antes da sua confirmação.'], props: [TASKS] }], comp: { attach: true, state: 'pending', note: 'nye.comp.pending' } } },
    'confirm-required': { vp: '924x540', d: 'Confirmação necessária · comunicação externa', app: { messages: [U_REVIEW, { steps: REVIEW_STEPS, blocks: ['O rascunho da revisão está pronto. O envio aos parceiros precisa da sua confirmação.'], props: [MAIL] }] }, confirm: MAIL },
    'exec-running': { vp: '1440x900', d: 'Execução · orquestração em curso', app: { messages: [U_REVIEW, { state: 'complete', steps: REVIEW_STEPS_RUN, stepsOpen: 1, blocks: ['A preparar a revisão semanal do Projeto Solander.'] }], comp: { attach: true, state: 'streaming' } } },
    'exec-completed': { vp: '924x540', d: 'Execução · concluída', app: { messages: [U_TASKS, { steps: [['Tarefas', 'Criou 3 tarefas', 'done']], blocks: [], props: [{ ...TASKS, state: 'completed', auth: 'authorized', details: 1, lines: TASKS.lines.map((l) => ({ ...l, ok: true, href: 1 })), cons: null, exec: { summary: '3 tarefas criadas no Projeto Solander.', audit: 'AUD-2026-09-29-7F3A', at: '29 set 2026, 10:46' } }] }] } },
    'exec-failed': { vp: '924x540', d: 'Execução · parcial / falhou', app: { messages: [U_TASKS, { steps: [['Tarefas', 'Criou 2 de 3 tarefas', 'failed']], blocks: [], props: [{ ...TASKS, state: 'partial', auth: 'authorized', details: 1, lines: [{ ...TASKS.lines[0], ok: true, href: 1 }, { ...TASKS.lines[1], ok: true, href: 1 }, { ...TASKS.lines[2], ok: false }], cons: null, exec: { error: 'partial_execution', detail: '«Actualizar o relatório de medições»: o Core recusou a atribuição.', audit: 'AUD-2026-09-29-7F3B', at: '29 set 2026, 10:46', retry: 0 } }] }] } },
    'app-new': { vp: '1440x900', d: 'Aplicação Nye · conversa nova', app: { newConv: 1 } },
    'app-active': { vp: '1440x900', d: 'Aplicação Nye · conversa activa', app: { messages: [Q_ASK, A_ASK, { role: 'member', at: '10:43', blocks: ['Que tarefas estão abertas por causa disto?'] }, { at: '10:43', steps: [['Tarefas', 'Encontrou 2 tarefas abertas', 'done']], blocks: ['Há duas tarefas abertas ligadas à campanha da torre 2:'], hits: [['task', [{ title: 'Rever a série da torre 2', ctx: 'Tarefas / Solander', meta: 'prazo 3 out · Ana Sebastião', app: 'Tarefas' }, { title: 'Substituir o registador do sensor 04', ctx: 'Tarefas / Solander', meta: 'prazo 8 out', app: 'Tarefas' }]]] }] } },
    'history': { vp: '390x844', d: 'Conversas · gaveta (móvel)', app: { messages: [Q_ASK, A_ASK], railOpen: 1 } },
    'history-gap': { vp: '924x540', d: 'Conversas · sem persistência no Core (lacuna honesta)', app: { messages: [Q_ASK, A_ASK], noHistory: 1 } },
    'sources-panel': { vp: '1440x900', d: 'Painel de fontes', app: { messages: [Q_ASK, A_ASK], panel: 'sources', panelSources: [...S_NOTES, { n: 5, k: 'web', title: 'Atlas eólico de Angola · Namibe', ctx: 'windatlas.exemplo.org', at: 'consultado hoje', ext: 1 }] } },
    'activity-panel': { vp: '1440x900', d: 'Painel de actividade', app: { messages: [U_REVIEW, { steps: REVIEW_STEPS, blocks: ['O rascunho da revisão está pronto.'] }], panel: 'activity', panelSteps: [['Pesquisa', 'Pesquisou «Solander» em tarefas e notas', 'done'], ...REVIEW_STEPS] } },
    'delegation': { vp: '924x540', d: 'Delegação em domínios · uma só Nye', app: { messages: [U_REVIEW, { steps: REVIEW_STEPS_RUN, stepsOpen: 1, blocks: [] }], comp: { attach: true, state: 'streaming' } } },
    'voice-idle': { vp: '924x540', d: 'Voz · pronta', app: { voice: { state: 'idle' } } },
    'voice-listening': { vp: '924x540', d: 'Voz · a ouvir', app: { voice: { state: 'listening' } } },
    'voice-transcribing': { vp: '924x540', d: 'Voz · a transcrever', app: { voice: { state: 'transcribing', transcript: 'Resume as últimas notas de investigação do Solander' } } },
    'voice-speaking': { vp: '924x540', d: 'Voz · a responder', app: { voice: { state: 'speaking', transcript: 'Resume as últimas notas de investigação do Solander', lang: 'pt', detected: 1 } } },
    'voice-unavailable': { vp: '924x540', d: 'Voz · indisponível', app: { voice: { state: 'unavailable', why: 'voice_unavailable' }, voiceOk: false } },
    'voice-mic-denied': { vp: '924x540', d: 'Voz · microfone recusado', app: { voice: { state: 'error', why: 'mic_denied' } } },
    'egress': { vp: '924x540', d: 'Processamento externo · aprovação pela política', app: { messages: [{ role: 'member', at: '10:50', blocks: ['Compara estas medições com o atlas eólico público.'] }, { at: '10:50', proc: 'approval', blocks: [] }, { role: 'member', at: '10:51', blocks: ['Resume o relatório confidencial do parceiro.'] }, { at: '10:51', proc: 'blocked', blocks: [] }] } },
    'permission-denied': { vp: '924x540', d: 'Permissão recusada pelo Core', app: { messages: [{ role: 'member', at: '10:52', blocks: ['Adiciona a Marta à equipa do Solander.'] }, { at: '10:52', blocks: [], props: [{ risk: 'privileged', auth: 'denied', state: 'blocked', title: 'Adicionar Marta Quintas à equipa do Projeto Solander', target: 'Projeto Solander · equipa', cap: 'workspace.membership.add', exec: { error: 'permission_denied' } }] }] } },
    'revoked': { vp: '924x540', d: 'Fonte revogada · conteúdo retirado', app: { messages: [Q_ASK, { at: '10:41', grounding: 'revoked', blocks: [{ p: SUMMARY[0].p, c: [1] }], sources: [S_NOTES[0], { n: 2, ok: false }, S_NOTES[2]] }] } },
    'ungrounded': { vp: '924x540', d: 'Resposta sem fontes do Ocinye', app: { messages: [{ role: 'member', at: '10:53', blocks: ['O que é a lei de potência do perfil de vento?'] }, { at: '10:53', grounding: 'none', blocks: ['É uma aproximação empírica que relaciona a velocidade do vento a duas alturas: v₂ = v₁ · (h₂ / h₁)^α, com α tipicamente entre 0,10 e 0,40 conforme a rugosidade do terreno.'], retry: 1 }] } },
    'context-unavailable': { vp: '924x540', d: 'Contexto indisponível', app: { ctx: { ...SOL, state: 'unavailable' }, ctxNote: 'unavailable', messages: [Q_ASK, { at: '10:41', fail: 'context_unavailable', blocks: [] }] } },
    'core-down': { vp: '924x540', d: 'Core indisponível · distinto de «sem IA»', surface: { avail: 'down', noApps: 0 } },
    'destructive': { vp: '924x540', d: 'Confirmação destrutiva (contrato de apresentação)', app: { messages: [{ role: 'member', at: '10:55', blocks: ['Apaga o projecto Piloto Huíla 2023.'] }, { blocks: [], props: [DEL] }] }, confirm: DEL },
    'tablet': { vp: '924x540', d: 'Tablet · Nye maximizada', app: { messages: [Q_ASK, A_ASK] } },
    'mobile': { vp: '390x844', d: 'Móvel · Nye em ecrã inteiro', app: { messages: [Q_ASK, A_ASK] } },
    'mobile-surface': { vp: '390x844', d: 'Móvel · superfície universal', surface: { q: 'vento', detected: 'search', hits: WIND.slice(0, 2), noApps: 1 } },
    'mobile-confirm': { vp: '390x844', d: 'Móvel · confirmação forte', app: { messages: [U_REVIEW, { blocks: [], props: [MAIL] }] }, confirm: MAIL },
    'closed-regression': { vp: '1440x900', d: 'Nye fechada · casca igual a D002.1', closed: 1 },
  };

  if (!S) { // índice
    document.getElementById('root').innerHTML = `<main style="font:14px var(--oc-sans);padding:24px;max-width:900px;margin:auto"><h1>D003 · Nye · referências</h1><ol>${Object.entries(STATES).map(([k, v]) => `<li><a href="?state=${k}&vp=${v.vp}${v.lang ? '&lang=' + v.lang : ''}">${k}</a> · ${v.d} · ${v.vp}</li>`).join('')}</ol></main>`;
    document.documentElement.setAttribute('data-fx-ready', '');
    return;
  }
  const st = STATES[S] || STATES['surface-empty'];
  document.documentElement.lang = { pt: 'pt-PT', en: 'en', fr: 'fr' }[LANG];
  let wins = [];
  if (st.app) wins = VW <= 640 ? [W(app(st.app), { state: 'maximized' })] : desktopWins(app(st.app));
  if (st.closed) wins = [{ app: 'files', id: 'f1', sub: 'Projectos / Solander', x: 40, y: 30, w: 560, h: 360, z: 1, body: FILES }, { app: 'notes', id: 'n1', sub: 'Reunião de unidade · 29 set', x: 420, y: 110, w: 520, h: 360, z: 2, active: 1, body: '<article class="fx-note"><h3>Reunião de unidade · 29 set</h3><p>Rever o plano de trabalho antes de sexta.</p></article>' }];
  const shell = `<div class="oc-shell">${topbar()}<div class="oc-desk" data-wall="ocinye" data-dim="20" data-wm="">${dock(wins)}<div class="oc-desk__work"><main class="oc-desk__main" id="oc-main"><div class="fx-desk-empty"></div></main><div class="oc-wm" data-oc="wm-layer">${wins.map(win).join('')}</div></div></div>${st.surface ? surface(st.surface) : ''}</div>${st.confirm ? confirmDlg(st.confirm) : ''}`;
  document.getElementById('root').innerHTML = `<div class="fx-board" data-vp="${VW}x${VH}">${shell}</div>`;
  const fx = document.createElement('style');
  fx.textContent = `html,body{height:100%;overflow:hidden;background:#0B1520}.fx-board{position:absolute;left:0;top:0;width:${VW}px;height:${VH}px;overflow:hidden;transform-origin:0 0;contain:layout paint}.fx-board .oc-shell{height:100%;min-height:0}.fx-files{padding:10px 14px}.fx-row{height:38px;display:grid;grid-template-columns:20px minmax(0,1fr) 80px 70px;align-items:center;gap:10px;border-bottom:1px solid var(--oc-line-2);font-size:13px}.fx-row small{color:var(--oc-ink-4);font-size:12px}.fx-note{max-width:560px;margin:0 auto;padding:26px 30px}.fx-note h3{margin:0 0 10px;font:600 18px var(--oc-sans)}.fx-note p{margin:0;color:var(--oc-ink-2)}.fx-desk-empty{height:100%}.oc-win__icon .oc-icon{color:#fff;stroke:#fff}.oc-nye__scroll:has(> .oc-nye-log){display:flex;flex-direction:column;justify-content:flex-end}.oc-nye__scroll > .oc-nye-log{flex:none}`;
  document.head.appendChild(fx);
  const fit = () => { const b = document.querySelector('.fx-board'); const s = Math.min(innerWidth / VW, innerHeight / VH); b.style.transform = `translate(${(innerWidth - VW * s) / 2}px, ${(innerHeight - VH * s) / 2}px) scale(${s})`; };
  fit(); addEventListener('resize', fit);
  for (const src of [ROOT + 'static/oc-shell.js', ROOT + 'static/oc-wm.js', ROOT + 'static/oc-nye.js']) {
    await new Promise((ok) => { const sc = document.createElement('script'); sc.src = src; sc.onload = ok; sc.onerror = ok; document.body.appendChild(sc); });
  }
  if (st.surface) document.querySelector('[data-oc="palette"]').setAttribute('data-open', '');
  document.documentElement.setAttribute('data-fx-ready', '');
  window.FX_STATES = STATES;
})();
