// Generated from the Design package D013 reference/d013/strings.js (pt, en, fr), unchanged.
// Regenerate rather than edit: the Design text is the source of truth.
pub const STRINGS: &[(&str, [&str; 3])] = &[
    ("st.unclaimed", ["NÃO RECLAMADO", "UNCLAIMED", "NON RÉCLAMÉ"]),
    ("st.claiming", ["A RECLAMAR", "CLAIM IN PROGRESS", "RÉCLAMATION EN COURS"]),
    ("st.claimed", ["RECLAMADO", "CLAIMED", "RÉCLAMÉ"]),
    ("st.locked", ["BLOQUEADO", "LOCKED", "VERROUILLÉ"]),
    ("st.claimFailed", ["FALHOU · RECUPERÁVEL", "FAILED · RECOVERABLE", "ÉCHEC · RÉCUPÉRABLE"]),
    ("c13.dev", ["COMPILAÇÃO DE DESENVOLVIMENTO · nunca para produção", "DEVELOPMENT BUILD · never for production", "COMPILATION DE DÉVELOPPEMENT · jamais en production"]),
    ("c13.state", ["Estado", "State", "État"]),
    ("c13.hostKey", ["Chave do anfitrião", "Host key", "Clé d’hôte"]),
    ("c13.network", ["Rede", "Network", "Réseau"]),
    ("c13.bootstrapId", ["Ident. de arranque", "Bootstrap ID", "Ident. d’amorçage"]),
    ("c13.warn", ["AVISO", "WARNING", "AVERT."]),
    ("c13.fail", ["FALHA", "FAILED", "ÉCHEC"]),
    ("c13.err.t", ["A instalação parou", "Installation stopped", "L’installation s’est arrêtée"]),
    ("c13.err.code", ["Código", "Code", "Code"]),
    ("c13.k.lang", ["Língua", "Language", "Langue"]),
    ("c13.k.reveal", ["Mostrar código", "Show code", "Afficher le code"]),
    ("c13.k.hide", ["Esconder", "Hide", "Masquer"]),
    ("c13.k.release", ["Libertar reclamação", "Release claim", "Libérer la réclamation"]),
    ("c13.k.unlock", ["Desbloquear", "Unlock", "Déverrouiller"]),
    ("c13.fb.t", ["A preparar esta máquina", "Preparing this machine", "Préparation de cette machine"]),
    ("c13.fb.note", ["Cada máquina criada a partir desta imagem gera aqui a sua própria identidade. Nada disto vem na imagem.", "Every machine created from this image generates its own identity here. None of it comes in the image.", "Chaque machine créée à partir de cette image génère ici sa propre identité. Rien de cela ne vient avec l’image."]),
    ("c13.e.identity", ["Não foi possível gerar a identidade desta máquina", "This machine’s identity could not be generated", "L’identité de cette machine n’a pas pu être générée"]),
    ("c13.e.identityB", ["As chaves do anfitrião SSH não foram criadas: entropia insuficiente após {s} s. A máquina não fica «Por reclamar» sem identidade própria.", "The SSH host keys were not created: insufficient entropy after {s} s. The machine does not become «Unclaimed» without its own identity.", "Les clés d’hôte SSH n’ont pas été créées : entropie insuffisante après {s} s. La machine ne devient pas « Non réclamée » sans identité propre."]),
    ("c13.e.identityN", ["Numa VM, acrescente um dispositivo virtio-rng e reinicie. O arranque volta a tentar e nunca reutiliza uma identidade parcial.", "In a VM, add a virtio-rng device and restart. Boot tries again and never reuses a partial identity.", "Dans une VM, ajoutez un périphérique virtio-rng et redémarrez. Le démarrage réessaie et ne réutilise jamais une identité partielle."]),
    ("c13.int.t", ["O release incluído não é o desta imagem", "The included release is not this image’s release", "Le release inclus n’est pas celui de cette image"]),
    ("c13.int.b", ["{f}: a soma não coincide com o manifesto da imagem. A reclamação está desligada; esta máquina não deve ser usada.", "{f}: the sum does not match the image manifest. Claiming is disabled; this machine must not be used.", "{f} : la somme ne correspond pas au manifeste de l’image. La réclamation est désactivée ; cette machine ne doit pas être utilisée."]),
    ("c13.int.n", ["Reinstale a partir de um suporte verificado.", "Reinstall from verified media.", "Réinstallez depuis un support vérifié."]),
    ("c13.un.t", ["Por reclamar", "Unclaimed", "Non réclamé"]),
    ("c13.un.b", ["Esta máquina ainda não pertence a ninguém. Para a reclamar, abra o Ocinye OS Installer no seu computador e ligue-se a um destes endereços com «Imagem Ocinye (emparelhar)».", "This machine does not belong to anyone yet. To claim it, open the Ocinye OS Installer on your computer and connect to one of these addresses with «Ocinye image (pair)».", "Cette machine n’appartient encore à personne. Pour la réclamer, ouvrez l’Ocinye OS Installer sur votre ordinateur et connectez-vous à l’une de ces adresses avec « Image Ocinye (appairer) »."]),
    ("c13.un.compare", ["Compare estes grupos com os que o Installer mostra:", "Compare these groups with those the Installer shows:", "Comparez ces groupes avec ceux qu’affiche l’Installer :"]),
    ("c13.un.code", ["Código de emparelhamento", "Pairing code", "Code d’appairage"]),
    ("c13.un.hidden", ["escondido · carregue em P para mostrar", "hidden · press P to show", "masqué · appuyez sur P pour afficher"]),
    ("c13.un.expires", ["válido até {t} · uma só vez · {n} tentativas", "valid until {t} · once · {n} attempts", "valable jusqu’à {t} · une seule fois · {n} tentatives"]),
    ("c13.un.shown", ["Visível nesta consola até carregar em P ou durante 60 s. Não o fotografe nem o envie por mensagem.", "Visible on this console until you press P or for 60 s. Do not photograph it or send it by message.", "Visible sur cette console jusqu’à ce que vous appuyiez sur P ou pendant 60 s. Ne le photographiez pas et ne l’envoyez pas par message."]),
    ("c13.un.serial", ["Na consola série, o código só aparece a pedido e nunca no registo de arranque.", "On the serial console the code appears only on request and never in the boot log.", "Sur la console série, le code n’apparaît que sur demande et jamais dans le journal de démarrage."]),
    ("c13.lock.t", ["Reclamação bloqueada", "Claiming locked", "Réclamation verrouillée"]),
    ("c13.lock.local", ["Quem está nesta consola pode desbloquear agora: carregue em U.", "Whoever is at this console can unlock now: press U.", "La personne présente à cette console peut déverrouiller maintenant : appuyez sur U."]),
    ("c13.cip.t", ["A reclamar", "Claim in progress", "Réclamation en cours"]),
    ("c13.cip.b", ["O código foi aceite e já não vale. À espera de que o Installer confirme com a chave autorizada.", "The code was accepted and no longer works. Waiting for the Installer to confirm with the authorized key.", "Le code a été accepté et n’est plus valable. En attente de la confirmation de l’Installer avec la clé autorisée."]),
    ("c13.cip.key", ["Chave a autorizar", "Key being authorized", "Clé en cours d’autorisation"]),
    ("c13.cip.deadline", ["Sem confirmação até {t}, a reclamação é desfeita e volta «Por reclamar».", "Without confirmation by {t}, the claim is rolled back to «Unclaimed».", "Sans confirmation avant {t}, la réclamation est annulée et revient à « Non réclamé »."]),
    ("c13.cf.t", ["A reclamação não terminou", "The claim did not finish", "La réclamation n’a pas abouti"]),
    ("c13.cl.t", ["Reclamado", "Claimed", "Réclamé"]),
    ("c13.cl.b", ["Esta máquina pertence à chave abaixo. A configuração do Ocinye OS continua no Installer. Esta consola mostra só o estado.", "This machine belongs to the key below. Ocinye OS configuration continues in the Installer. This console shows status only.", "Cette machine appartient à la clé ci-dessous. La configuration d’Ocinye OS se poursuit dans l’Installer. Cette console n’affiche que l’état."]),
    ("c13.cl.owner", ["Chave dona", "Owner key", "Clé propriétaire"]),
    ("c13.cl.when", ["Reclamado em", "Claimed at", "Réclamé le"]),
    ("c13.cl.release", ["Libertar a reclamação só é possível nesta consola e apenas antes de existir uma Instância.", "Releasing the claim is possible only at this console and only before an Instance exists.", "Libérer la réclamation n’est possible que sur cette console et seulement avant qu’une Instance existe."]),
    ("c13.netw.t", ["À espera de rede", "Waiting for network", "En attente du réseau"]),
];
