/* Ocinye OS Installer · D011 · textos pt (canónico) · en · fr.
   Cada chave tem exactamente três textos. Valores de exemplo só com domínios
   .test / example.com e endereços de documentação (192.0.2.0/24, 2001:db8::/32).
   Nenhum segredo real: as credenciais são marcadores fictícios evidentes. */
window.OI_T = {
  // ── moldura
  'app.name': ['Ocinye OS Installer', 'Ocinye OS Installer', 'Ocinye OS Installer'],
  'app.sub': ['INSTALADOR', 'INSTALLER', 'INSTALLATEUR'],
  'rail.prepare': ['PREPARAR', 'PREPARE', 'PRÉPARER'],
  'rail.configure': ['CONFIGURAR', 'CONFIGURE', 'CONFIGURER'],
  'rail.install': ['INSTALAR', 'INSTALL', 'INSTALLER'],
  'rail.version': ['Instalador', 'Installer', 'Installateur'],
  'rail.platform': ['Este computador', 'This computer', 'Cet ordinateur'],
  'rail.target': ['Servidor', 'Server', 'Serveur'],
  'rail.blocked': ['BLOQUEADO', 'BLOCKED', 'BLOQUÉ'],
  'step.release': ['Release', 'Release', 'Version'],
  'step.server': ['Servidor', 'Server', 'Serveur'],
  'step.trust': ['Identidade do servidor', 'Server identity', 'Identité du serveur'],
  'step.preflight': ['Verificação prévia', 'Preflight', 'Vérification préalable'],
  'step.hardware': ['Hardware e computação', 'Hardware & compute', 'Matériel et calcul'],
  'step.instance': ['Instância', 'Instance', 'Instance'],
  'step.dists': ['Distribuições', 'Distributions', 'Distributions'],
  'step.endpoints': ['Pontos de acesso', 'Access endpoints', 'Points d’accès'],
  'step.tls': ['Certificado TLS', 'TLS certificate', 'Certificat TLS'],
  'step.admin': ['Primeiro administrador', 'First administrator', 'Premier administrateur'],
  'step.review': ['Revisão', 'Review', 'Revue'],
  'step.install': ['Instalação', 'Installation', 'Installation'],
  'step.verify': ['Verificação', 'Verification', 'Vérification'],
  'step.done': ['Concluído', 'Complete', 'Terminé'],
  'kicker.step': ['PASSO {n} DE 14', 'STEP {n} OF 14', 'ÉTAPE {n} SUR 14'],
  'kicker.start': ['INÍCIO', 'START', 'DÉBUT'],
  'kicker.recovery': ['RECUPERAÇÃO', 'RECOVERY', 'RÉCUPÉRATION'],
  'kicker.stopped': ['INSTALAÇÃO PARADA', 'INSTALLATION STOPPED', 'INSTALLATION ARRÊTÉE'],

  // ── acções
  'a.start': ['Começar', 'Start', 'Commencer'],
  'a.continue': ['Continuar', 'Continue', 'Continuer'],
  'a.back': ['Voltar', 'Back', 'Retour'],
  'a.cancel': ['Cancelar', 'Cancel', 'Annuler'],
  'a.close': ['Fechar instalador', 'Close installer', 'Fermer l’installateur'],
  'a.retry': ['Tentar novamente', 'Try again', 'Réessayer'],
  'a.recheck': ['Verificar novamente', 'Check again', 'Vérifier à nouveau'],
  'a.choose': ['Escolher…', 'Choose…', 'Choisir…'],
  'a.change': ['Alterar', 'Change', 'Modifier'],
  'a.details': ['Ver detalhes', 'View details', 'Voir les détails'],
  'a.openBundle': ['Abrir pacote…', 'Open package…', 'Ouvrir le paquet…'],
  'a.otherBundle': ['Escolher outro pacote', 'Choose another package', 'Choisir un autre paquet'],
  'a.test': ['Testar ligação', 'Test connection', 'Tester la connexion'],
  'a.trust': ['Confiar neste servidor', 'Trust this server', 'Faire confiance à ce serveur'],
  'a.otherServer': ['Ligar a outro servidor', 'Connect to another server', 'Se connecter à un autre serveur'],
  'a.install': ['Instalar Ocinye OS', 'Install Ocinye OS', 'Installer Ocinye OS'],
  'a.stop': ['Parar num ponto seguro', 'Stop at a safe point', 'Arrêter à un point sûr'],
  'a.reconnect': ['Voltar a ligar', 'Reconnect', 'Se reconnecter'],
  'a.resume': ['Retomar instalação', 'Resume installation', 'Reprendre l’installation'],
  'a.removeIncomplete': ['Remover instalação incompleta', 'Remove incomplete installation', 'Supprimer l’installation incomplète'],
  'a.saveReport': ['Guardar relatório', 'Save report', 'Enregistrer le rapport'],
  'a.open': ['Abrir Ocinye OS', 'Open Ocinye OS', 'Ouvrir Ocinye OS'],
  'a.show': ['Mostrar', 'Show', 'Afficher'],
  'a.copy': ['Copiar', 'Copy', 'Copier'],
  'a.saved': ['Já a guardei', 'I have saved it', 'Je l’ai enregistré'],
  'a.addEndpoint': ['Acrescentar ponto de acesso', 'Add access endpoint', 'Ajouter un point d’accès'],
  'a.remove': ['Remover', 'Remove', 'Retirer'],
  'a.sudoOk': ['Confirmar', 'Confirm', 'Confirmer'],
  'a.credential': ['Ver credencial temporária', 'View temporary credential', 'Voir l’identifiant temporaire'],
  'a.receipt': ['Ver relatório', 'View report', 'Voir le rapport'],
  'a.newPlan': ['Rever configuração', 'Review configuration', 'Revoir la configuration'],

  // ── estados (texto que acompanha a cor)
  'st.pass': ['PASSA', 'PASS', 'RÉUSSI'],
  'st.warn': ['AVISO', 'WARNING', 'AVERTISSEMENT'],
  'st.block': ['BLOQUEADO', 'BLOCKED', 'BLOQUÉ'],
  'st.na': ['NÃO APLICÁVEL', 'NOT APPLICABLE', 'NON APPLICABLE'],
  'st.valid': ['VÁLIDO', 'VALID', 'VALIDE'],
  'st.invalid': ['INVÁLIDO', 'INVALID', 'INVALIDE'],
  'st.detected': ['DETECTADO', 'DETECTED', 'DÉTECTÉ'],
  'st.unavailable': ['INDISPONÍVEL', 'UNAVAILABLE', 'INDISPONIBLE'],
  'st.unknown': ['DESCONHECIDO', 'UNKNOWN', 'INCONNU'],
  'st.running': ['A DECORRER', 'RUNNING', 'EN COURS'],
  'st.done': ['FEITO', 'DONE', 'FAIT'],
  'st.failed': ['FALHOU', 'FAILED', 'ÉCHEC'],
  'st.todo': ['POR FAZER', 'PENDING', 'À FAIRE'],
  'st.future': ['FUTURO', 'FUTURE', 'FUTUR'],
  'st.notConfigured': ['NÃO CONFIGURADO', 'NOT CONFIGURED', 'NON CONFIGURÉ'],
  'st.dev': ['DEVELOPMENT BUILD', 'DEVELOPMENT BUILD', 'DEVELOPMENT BUILD'],
  'st.release': ['RELEASE', 'RELEASE', 'RELEASE'],
  'st.dnsOk': ['DNS CORRECTO', 'DNS CORRECT', 'DNS CORRECT'],
  'st.dnsChecking': ['A VERIFICAR', 'CHECKING', 'VÉRIFICATION'],
  'st.dnsWrong': ['OUTRO DESTINO', 'WRONG TARGET', 'MAUVAISE CIBLE'],
  'st.dnsUnresolved': ['SEM REGISTO', 'UNRESOLVED', 'NON RÉSOLU'],
  'st.dnsRequired': ['DNS NECESSÁRIO', 'DNS REQUIRED', 'DNS REQUIS'],
  'st.test': ['TESTE / DESENVOLVIMENTO', 'TEST / DEVELOPMENT', 'TEST / DÉVELOPPEMENT'],
  'st.readOnly': ['SÓ LEITURA', 'READ-ONLY', 'LECTURE SEULE'],
  'st.pending': ['PENDENTE', 'PENDING', 'EN ATTENTE'],
  'st.immutable': ['PLANO FIXO', 'PLAN LOCKED', 'PLAN FIGÉ'],

  // ── I01 boas-vindas
  'welcome.title': ['Instalar Ocinye OS', 'Install Ocinye OS', 'Installer Ocinye OS'],
  'welcome.lead': ['Instala o Ocinye OS num servidor remoto compatível.', 'Installs Ocinye OS on a compatible remote server.', 'Installe Ocinye OS sur un serveur distant compatible.'],
  'welcome.need': ['O que vai precisar', 'What you will need', 'Ce dont vous aurez besoin'],
  'welcome.need1': ['Um pacote de release do Ocinye OS neste computador.', 'An Ocinye OS release package on this computer.', 'Un paquet de version d’Ocinye OS sur cet ordinateur.'],
  'welcome.need2': ["Um servidor Debian 12 ou Ubuntu 24.04 LTS de 64 bits — ou outro Linux de 64 bits que já tenha Docker Engine 24 ou mais recente — com acesso SSH e sudo. O instalador instala o Docker quando falta.","A 64-bit Debian 12 or Ubuntu 24.04 LTS server — or another 64-bit Linux that already has Docker Engine 24 or newer — with SSH and sudo access. The installer installs Docker when it is missing.","Un serveur Debian 12 ou Ubuntu 24.04 LTS 64 bits — ou un autre Linux 64 bits disposant déjà de Docker Engine 24 ou plus récent — avec accès SSH et sudo. L’installateur installe Docker s’il manque."],
  'welcome.need3': ['Os nomes de domínio que as pessoas vão usar e, para uso real, o certificado TLS desses nomes.', 'The domain names people will use and, for real use, the TLS certificate for those names.', 'Les noms de domaine que les personnes utiliseront et, en usage réel, le certificat TLS de ces noms.'],
  'welcome.safe': ['Nada é alterado no servidor antes de rever e confirmar o plano de instalação.', 'Nothing is changed on the server until you review and confirm the installation plan.', 'Rien n’est modifié sur le serveur avant que vous ayez revu et confirmé le plan d’installation.'],
  'welcome.facts': ['Este instalador', 'This installer', 'Cet installateur'],
  'welcome.version': ['Versão', 'Version', 'Version'],
  'welcome.platform': ['Plataforma local', 'Local platform', 'Plateforme locale'],
  'welcome.source': ['Origem das releases', 'Release source', 'Source des versions'],
  'welcome.sourceV': ['Pacote local (não existe canal de releases)', 'Local package (no release channel exists)', 'Paquet local (aucun canal de versions n’existe)'],
  'welcome.scope': ['Âmbito', 'Scope', 'Portée'],
  'welcome.scopeV': ['Instalação nova. Actualizar, reparar e desinstalar não fazem parte desta versão.', 'Fresh installation. Upgrade, repair and uninstall are not part of this version.', 'Nouvelle installation. Mise à niveau, réparation et désinstallation ne font pas partie de cette version.'],

  // ── I02 release
  'release.title': ['Release a instalar', 'Release to install', 'Version à installer'],
  'release.lead': ['O instalador instala exactamente um release imutável. As somas SHA-256 do pacote são conferidas aqui e de novo no servidor depois da transferência.', 'The installer installs exactly one immutable release. The package SHA-256 sums are checked here and again on the server after transfer.', 'L’installateur installe exactement une version immuable. Les sommes SHA-256 du paquet sont vérifiées ici puis à nouveau sur le serveur après le transfert.'],
  'release.package': ['Pacote', 'Package', 'Paquet'],
  'release.id': ['Release', 'Release', 'Version'],
  'release.commit': ['Commit', 'Commit', 'Commit'],
  'release.build': ['Tipo de build', 'Build type', 'Type de build'],
  'release.arch': ['Arquitectura', 'Architecture', 'Architecture'],
  'release.target': ['Sistema de destino', 'Target system', 'Système cible'],
  'release.migrations': ['Migrações', 'Migrations', 'Migrations'],
  'release.artifacts': ['Artefactos', 'Artifacts', 'Artefacts'],
  'release.integrity': ['Integridade', 'Integrity', 'Intégrité'],
  'release.integrityV': ['{n} ficheiros · somas SHA-256 conferidas neste computador', '{n} files · SHA-256 sums checked on this computer', '{n} fichiers · sommes SHA-256 vérifiées sur cet ordinateur'],
  'release.signing': ['Assinatura', 'Signature', 'Signature'],
  'release.signingV': ['Não existe. As somas provam integridade, não origem: obtenha o pacote por um canal em que confia.', 'None. The sums prove integrity, not origin: obtain the package through a channel you trust.', 'Aucune. Les sommes prouvent l’intégrité, pas l’origine : obtenez le paquet par un canal de confiance.'],
  'release.dev': ['DEVELOPMENT BUILD · pacote de prova, sem LTO · nunca para produção', 'DEVELOPMENT BUILD · proof package, no LTO · never for production', 'DEVELOPMENT BUILD · paquet de preuve, sans LTO · jamais en production'],
  'release.devAlertT': ['Este pacote é um build de desenvolvimento', 'This package is a development build', 'Ce paquet est un build de développement'],
  'release.devAlertB': ['Serve para provas e laboratório. A instalação fica marcada como tal no relatório e não deve servir pessoas em uso real.', 'It is for proofs and labs. The installation is marked as such in the report and must not serve people in real use.', 'Il sert aux preuves et aux laboratoires. L’installation est marquée comme telle dans le rapport et ne doit pas servir des personnes en usage réel.'],
  'release.checksumT': ['As somas do pacote não conferem', 'The package sums do not match', 'Les sommes du paquet ne correspondent pas'],
  'release.checksumB': ['{f} não corresponde a SHA256SUMS. Um pacote alterado não se instala. Obtenha de novo o pacote por um canal em que confia.', '{f} does not match SHA256SUMS. A modified package is never installed. Obtain the package again through a channel you trust.', '{f} ne correspond pas à SHA256SUMS. Un paquet modifié n’est jamais installé. Obtenez à nouveau le paquet par un canal de confiance.'],
  'release.archT': ['Arquitectura não suportada', 'Unsupported architecture', 'Architecture non prise en charge'],
  'release.archB': ['O pacote foi construído para {a}. O Ocinye OS publica pacotes para amd64 e arm64.', 'The package was built for {a}. Ocinye OS publishes packages for amd64 and arm64.', 'Le paquet a été construit pour {a}. Ocinye OS publie des paquets pour amd64 et arm64.'],
  'release.manifestT': ['O manifesto do pacote é inválido', 'The package manifest is invalid', 'Le manifeste du paquet est invalide'],
  'release.manifestB': ['MANIFEST.json não tem o campo obrigatório «{k}». Sem um manifesto completo o instalador não sabe o que está a instalar.', 'MANIFEST.json is missing the required field “{k}”. Without a complete manifest the installer cannot know what it is installing.', 'MANIFEST.json ne contient pas le champ obligatoire « {k} ». Sans manifeste complet, l’installateur ne sait pas ce qu’il installe.'],
  'release.targetT': ['Este pacote não serve o servidor escolhido', 'This package does not fit the selected server', 'Ce paquet ne convient pas au serveur choisi'],
  'release.targetB': ['O pacote é {a}; o servidor {h} é {b}. Escolha o pacote da arquitectura do servidor.', 'The package is {a}; server {h} is {b}. Choose the package for the server’s architecture.', 'Le paquet est {a} ; le serveur {h} est {b}. Choisissez le paquet de l’architecture du serveur.'],
  'release.stop': ['Paragem definitiva: nada foi enviado ao servidor.', 'Hard stop: nothing was sent to the server.', 'Arrêt définitif : rien n’a été envoyé au serveur.'],

  // ── I03 servidor
  'server.title': ['Ligar ao servidor', 'Connect to the server', 'Se connecter au serveur'],
  'server.lead': ['A ligação usa SSH como transporte. O teste é só de leitura: lê o sistema, a arquitectura e os privilégios, e não escreve nada.', 'The connection uses SSH as transport. The test is read-only: it reads the system, architecture and privileges, and writes nothing.', 'La connexion utilise SSH comme transport. Le test est en lecture seule : il lit le système, l’architecture et les privilèges, et n’écrit rien.'],
  'server.host': ['Endereço do servidor', 'Server address', 'Adresse du serveur'],
  'server.hostHint': ['Nome de anfitrião, IPv4 ou IPv6. Sem esquema, caminho ou espaços.', 'Hostname, IPv4 or IPv6. No scheme, path or spaces.', 'Nom d’hôte, IPv4 ou IPv6. Sans schéma, chemin ni espaces.'],
  'server.port': ['Porta SSH', 'SSH port', 'Port SSH'],
  'server.user': ['Utilizador SSH', 'SSH user', 'Utilisateur SSH'],
  'server.userHint': ['Recomendado: um utilizador normal com sudo. Não é preciso entrar como root.', 'Recommended: a normal user with sudo. Logging in as root is not required.', 'Recommandé : un utilisateur normal avec sudo. Il n’est pas nécessaire de se connecter en root.'],
  'server.auth': ['Autenticação', 'Authentication', 'Authentification'],
  'server.agent': ['Agente SSH', 'SSH agent', 'Agent SSH'],
  'server.key': ['Chave privada', 'Private key', 'Clé privée'],
  'server.password': ['Palavra-passe', 'Password', 'Mot de passe'],
  'server.agentV': ['Usa as chaves do agente deste computador. Nenhuma chave sai deste computador.', 'Uses the keys in this computer’s agent. No key leaves this computer.', 'Utilise les clés de l’agent de cet ordinateur. Aucune clé ne quitte cet ordinateur.'],
  'server.keyHint': ['O conteúdo da chave nunca é mostrado nem enviado ao servidor.', 'The key contents are never shown or sent to the server.', 'Le contenu de la clé n’est jamais affiché ni envoyé au serveur.'],
  'server.pwHint': ['Usada só nesta sessão. Não é guardada nem registada.', 'Used only in this session. Never stored or logged.', 'Utilisé uniquement pendant cette session. Jamais enregistré ni journalisé.'],
  'server.tested': ['Resultado do teste', 'Test result', 'Résultat du test'],
  'server.hostname': ['Nome do anfitrião', 'Hostname', 'Nom d’hôte'],
  'server.os': ['Sistema', 'System', 'Système'],
  'server.privilege': ['Privilégio', 'Privilege', 'Privilège'],
  'server.privSudo': ['sudo disponível (pede palavra-passe)', 'sudo available (asks for password)', 'sudo disponible (demande un mot de passe)'],
  'server.unreachT': ['O servidor não respondeu', 'The server did not respond', 'Le serveur n’a pas répondu'],
  'server.unreachB': ['Não houve resposta de {h} na porta {p} em 15 s. Confirme o endereço, a porta e se uma firewall permite SSH a partir deste computador.', 'No response from {h} on port {p} within 15 s. Check the address, the port and whether a firewall allows SSH from this computer.', 'Aucune réponse de {h} sur le port {p} en 15 s. Vérifiez l’adresse, le port et qu’un pare-feu autorise SSH depuis cet ordinateur.'],
  'server.authT': ['O servidor recusou a autenticação', 'The server refused authentication', 'Le serveur a refusé l’authentification'],
  'server.authB': ['{u}@{h} não aceitou as chaves do agente SSH. O servidor não diz porquê; confirme o utilizador e a chave autorizada.', '{u}@{h} did not accept the SSH agent keys. The server does not say why; check the user and the authorized key.', '{u}@{h} n’a pas accepté les clés de l’agent SSH. Le serveur n’indique pas pourquoi ; vérifiez l’utilisateur et la clé autorisée.'],
  'server.hostInvalid': ['«{v}» não é um nome de anfitrião nem um endereço IP.', '“{v}” is not a hostname or IP address.', '« {v} » n’est ni un nom d’hôte ni une adresse IP.'],

  // ── I04 identidade do servidor
  'trust.title': ['Confirmar a identidade do servidor', 'Confirm the server’s identity', 'Confirmer l’identité du serveur'],
  'trust.lead': ['É a primeira ligação a este servidor. Compare a impressão digital com a que o fornecedor ou o administrador do servidor lhe deu, por outro canal.', 'This is the first connection to this server. Compare the fingerprint with the one the provider or server administrator gave you through another channel.', 'C’est la première connexion à ce serveur. Comparez l’empreinte avec celle que le fournisseur ou l’administrateur du serveur vous a donnée par un autre canal.'],
  'trust.server': ['Servidor', 'Server', 'Serveur'],
  'trust.alg': ['Algoritmo da chave', 'Key algorithm', 'Algorithme de la clé'],
  'trust.fp': ['Impressão digital', 'Fingerprint', 'Empreinte'],
  'trust.note': ['Ao confiar, a chave fica registada para este servidor neste computador. Uma chave diferente numa ligação futura pára o instalador.', 'When you trust it, the key is recorded for this server on this computer. A different key on a future connection stops the installer.', 'En lui faisant confiance, la clé est enregistrée pour ce serveur sur cet ordinateur. Une clé différente lors d’une connexion future arrête l’installateur.'],
  'trust.mismatchT': ['A chave deste servidor mudou', 'This server’s key has changed', 'La clé de ce serveur a changé'],
  'trust.mismatchB': ['{h} apresenta uma chave diferente da registada a {d}. Pode ser uma reinstalação do servidor ou alguém entre este computador e o servidor. O instalador não continua.', '{h} presents a key different from the one recorded on {d}. It may be a server reinstallation or someone between this computer and the server. The installer will not continue.', '{h} présente une clé différente de celle enregistrée le {d}. Il peut s’agir d’une réinstallation du serveur ou de quelqu’un entre cet ordinateur et le serveur. L’installateur ne continue pas.'],
  'trust.known': ['Chave registada', 'Recorded key', 'Clé enregistrée'],
  'trust.presented': ['Chave apresentada agora', 'Key presented now', 'Clé présentée maintenant'],
  'trust.mismatchNext': ['Confirme com quem administra o servidor. Se a mudança for legítima, remova a chave antiga deste computador pela opção «Esquecer servidor» nas definições do instalador, que exige confirmar a nova impressão digital.', 'Confirm with whoever administers the server. If the change is legitimate, remove the old key from this computer with “Forget server” in the installer settings, which requires confirming the new fingerprint.', 'Confirmez avec la personne qui administre le serveur. Si le changement est légitime, retirez l’ancienne clé de cet ordinateur avec « Oublier le serveur » dans les réglages de l’installateur, qui exige de confirmer la nouvelle empreinte.'],

  // ── privilégio
  'priv.title': ['Palavra-passe de sudo', 'sudo password', 'Mot de passe sudo'],
  'priv.body': ['{u} precisa de sudo para a verificação prévia ler portas e serviços, e mais tarde para instalar. A palavra-passe fica só em memória durante esta sessão.', '{u} needs sudo for the preflight to read ports and services, and later to install. The password stays in memory only for this session.', '{u} a besoin de sudo pour que la vérification préalable lise les ports et services, puis pour installer. Le mot de passe reste uniquement en mémoire pendant cette session.'],
  'priv.field': ['Palavra-passe de {u}', 'Password for {u}', 'Mot de passe de {u}'],
  'priv.missingT': ['Este utilizador não tem privilégios de administração', 'This user has no administrative privileges', 'Cet utilisateur n’a pas de privilèges d’administration'],
  'priv.missingB': ['{u} não pertence aos sudoers de {h}. A instalação escreve em /srv/ocinye e /etc/ocinye e gere o Docker, por isso precisa de sudo ou de root. O instalador não altera a configuração de SSH nem de sudo.', '{u} is not in the sudoers of {h}. The installation writes to /srv/ocinye and /etc/ocinye and manages Docker, so it needs sudo or root. The installer does not change SSH or sudo configuration.', '{u} ne fait pas partie des sudoers de {h}. L’installation écrit dans /srv/ocinye et /etc/ocinye et gère Docker ; elle exige donc sudo ou root. L’installateur ne modifie pas la configuration SSH ni sudo.'],

  // ── I06 verificação prévia
  'pre.title': ['Verificação prévia', 'Preflight', 'Vérification préalable'],
  'pre.lead': ['Lê o servidor sem o alterar: sistema, recursos, Docker, portas e instalações existentes.', 'Reads the server without changing it: system, resources, Docker, ports and existing installations.', 'Lit le serveur sans le modifier : système, ressources, Docker, ports et installations existantes.'],
  'pre.running': ['A verificar {n} de {m}…', 'Checking {n} of {m}…', 'Vérification {n} sur {m}…'],
  'pre.sum': ['{p} passam · {w} avisos · {b} bloqueados', '{p} pass · {w} warnings · {b} blocked', '{p} réussis · {w} avertissements · {b} bloqués'],
  'pre.g.system': ['SISTEMA', 'SYSTEM', 'SYSTÈME'],
  'pre.g.resources': ['RECURSOS', 'RESOURCES', 'RESSOURCES'],
  'pre.g.runtime': ['RUNTIME E REDE', 'RUNTIME AND NETWORK', 'RUNTIME ET RÉSEAU'],
  'pre.g.existing': ['O QUE JÁ LÁ ESTÁ', 'WHAT IS ALREADY THERE', 'CE QUI EST DÉJÀ LÀ'],
  'pre.os': ['Linux de 64 bits', '64-bit Linux', 'Linux 64 bits'],
  'pre.osD': ['{v} · núcleo {k}. Nenhuma distribuição é certificada; o requisito é Linux com Docker.', '{v} · kernel {k}. No distribution is certified; the requirement is Linux with Docker.', '{v} · noyau {k}. Aucune distribution n’est certifiée ; l’exigence est Linux avec Docker.'],
  'pre.arch': ['Arquitectura igual à do pacote', 'Architecture matches the package', 'Architecture identique au paquet'],
  'pre.archD': ['servidor {a} · pacote {b}', 'server {a} · package {b}', 'serveur {a} · paquet {b}'],
  'pre.priv': ['Privilégio de administração', 'Administrative privilege', 'Privilège d’administration'],
  'pre.privD': ['sudo confirmado para {u}', 'sudo confirmed for {u}', 'sudo confirmé pour {u}'],
  'pre.time': ['Relógio do sistema', 'System clock', 'Horloge système'],
  'pre.timeD': ['Diferença de {s} s para este computador. Certificados e sessões dependem da hora certa.', '{s} s difference from this computer. Certificates and sessions depend on correct time.', 'Écart de {s} s avec cet ordinateur. Les certificats et les sessions dépendent de l’heure exacte.'],
  'pre.cpu': ['Processador', 'Processor', 'Processeur'],
  'pre.cpuD': ['{n} vCPU · mínimo suportado 2, recomendado 4', '{n} vCPU · supported minimum 2, recommended 4', '{n} vCPU · minimum pris en charge 2, recommandé 4'],
  'pre.ram': ['Memória', 'Memory', 'Mémoire'],
  'pre.ramD': ['{v} · o instalador recusa menos de 3,5 GB; recomendado 8 GB', '{v} · the installer refuses less than 3.5 GB; recommended 8 GB', '{v} · l’installateur refuse moins de 3,5 Go ; recommandé 8 Go'],
  'pre.ramWarn': ['{v} · abaixo dos 8 GB recomendados: conversões de ficheiros e vários membros ao mesmo tempo ficam mais lentos', '{v} · below the recommended 8 GB: file conversions and several members at once will be slower', '{v} · en dessous des 8 Go recommandés : conversions de fichiers et plusieurs membres simultanés seront plus lents'],
  'pre.disk': ['Espaço livre em /srv', 'Free space in /srv', 'Espace libre dans /srv'],
  'pre.diskD': ['{v} livres · mínimo 15 GB', '{v} free · minimum 15 GB', '{v} libres · minimum 15 Go'],
  'pre.diskBlock': ['{v} livres em /srv · o mínimo é 15 GB. Liberte espaço ou aumente o disco e verifique novamente.', '{v} free in /srv · the minimum is 15 GB. Free up space or enlarge the disk and check again.', '{v} libres dans /srv · le minimum est 15 Go. Libérez de l’espace ou agrandissez le disque puis vérifiez à nouveau.'],
  'pre.docker': ['Docker Engine e Compose', 'Docker Engine and Compose', 'Docker Engine et Compose'],
  'pre.dockerD': ['Engine {v} · compose v2 · a correr', 'Engine {v} · compose v2 · running', 'Engine {v} · compose v2 · en cours d’exécution'],
  'pre.ports': ['Portas 80 e 443 livres', 'Ports 80 and 443 free', 'Ports 80 et 443 libres'],
  'pre.portsD': ['Nenhum processo escuta em 80 nem em 443', 'No process listens on 80 or 443', 'Aucun processus n’écoute sur 80 ni 443'],
  'pre.portsBlock': ['A porta 443 está ocupada por {p}. O Ocinye OS não substitui um serviço que não é seu: pare-o ou use outro servidor.', 'Port 443 is taken by {p}. Ocinye OS does not replace a service it does not own: stop it or use another server.', 'Le port 443 est occupé par {p}. Ocinye OS ne remplace pas un service qui ne lui appartient pas : arrêtez-le ou utilisez un autre serveur.'],
  'pre.registry': ['Acesso aos registries de imagens', 'Access to image registries', 'Accès aux registres d’images'],
  'pre.registryD': ['As imagens de terceiros (PostgreSQL, Redis, Garage, nginx) descarregam-se durante a instalação', 'Third-party images (PostgreSQL, Redis, Garage, nginx) are downloaded during installation', 'Les images tierces (PostgreSQL, Redis, Garage, nginx) sont téléchargées pendant l’installation'],
  'pre.existing': ['Nenhum Ocinye OS instalado', 'No Ocinye OS installed', 'Aucun Ocinye OS installé'],
  'pre.existingD': ['/etc/ocinye e /srv/ocinye não existem', '/etc/ocinye and /srv/ocinye do not exist', '/etc/ocinye et /srv/ocinye n’existent pas'],
  'pre.journal': ['Nenhuma instalação incompleta', 'No incomplete installation', 'Aucune installation incomplète'],
  'pre.journalD': ['Sem diário de instalação neste servidor', 'No installation journal on this server', 'Aucun journal d’installation sur ce serveur'],
  'pre.systemd': ['systemd', 'systemd', 'systemd'],
  'pre.systemdD': ['Presente: o Ocinye OS volta a arrancar depois de um reboot', 'Present: Ocinye OS starts again after a reboot', 'Présent : Ocinye OS redémarre après un redémarrage'],
  'pre.proxyConflict': ['Outro proxy inverso', 'Another reverse proxy', 'Autre proxy inverse'],
  'pre.blockedT': ['A instalação não pode continuar', 'Installation cannot continue', 'L’installation ne peut pas continuer'],
  'pre.blockedB': ['Uma condição obrigatória não é cumprida. Nada foi alterado no servidor. Corrija-a fora do instalador e verifique novamente.', 'A mandatory condition is not met. Nothing was changed on the server. Fix it outside the installer and check again.', 'Une condition obligatoire n’est pas remplie. Rien n’a été modifié sur le serveur. Corrigez-la en dehors de l’installateur puis vérifiez à nouveau.'],
  'pre.warnT': ['Pode continuar, com avisos', 'You can continue, with warnings', 'Vous pouvez continuer, avec des avertissements'],
  'pre.warnB': ['Os avisos não impedem a instalação e ficam no relatório.', 'Warnings do not prevent installation and are kept in the report.', 'Les avertissements n’empêchent pas l’installation et figurent dans le rapport.'],
  'pre.existsT': ['Ocinye OS já está instalado neste servidor.', 'Ocinye OS is already installed on this server.', 'Ocinye OS est déjà installé sur ce serveur.'],
  'pre.existsB': ['Encontrado /etc/ocinye/core.env (release {r}). Uma instalação nova por cima apagaria a raiz de selagem de dados que existem. Esta versão do instalador não actualiza instalações.', 'Found /etc/ocinye/core.env (release {r}). A fresh installation over it would destroy the sealing root of existing data. This installer version does not upgrade installations.', '/etc/ocinye/core.env trouvé (version {r}). Une nouvelle installation par-dessus détruirait la racine de scellement de données existantes. Cette version de l’installateur ne met pas à niveau les installations.'],
  'pre.dockerMissing': ['Docker não encontrado', 'Docker not found', 'Docker introuvable'],
  'pre.hwVisible': ['Hardware legível', 'Hardware readable', 'Matériel lisible'],
  'pre.hwVisibleD': ['/proc, /sys e o bus PCI são legíveis', '/proc, /sys and the PCI bus are readable', '/proc, /sys et le bus PCI sont lisibles'],

  // ── I19 instalação incompleta
  'inc.title': ['Há uma instalação incompleta neste servidor', 'There is an incomplete installation on this server', 'Il y a une installation incomplète sur ce serveur'],
  'inc.lead': ['O diário de instalação diz onde parou. O instalador nunca repete uma instalação desde o início sobre o que já foi feito.', 'The installation journal says where it stopped. The installer never replays an installation from the start over what was already done.', 'Le journal d’installation indique où elle s’est arrêtée. L’installateur ne rejoue jamais une installation depuis le début sur ce qui a déjà été fait.'],
  'inc.id': ['Instalação', 'Installation', 'Installation'],
  'inc.release': ['Release', 'Release', 'Version'],
  'inc.state': ['Estado', 'State', 'État'],
  'inc.stateV': ['INTERROMPIDA · o bootstrap deixou de responder', 'INTERRUPTED · the bootstrap stopped responding', 'INTERROMPUE · le bootstrap ne répond plus'],
  'inc.phases': ['Fases', 'Phases', 'Phases'],
  'inc.phasesV': ["P01–P08 feitas · P09 por confirmar","P01–P08 done · P09 unconfirmed","P01–P08 faites · P09 non confirmée"],
  'inc.when': ['Último evento', 'Last event', 'Dernier événement'],
  'inc.resumeT': ['Pode retomar', 'You can resume', 'Vous pouvez reprendre'],
  'inc.resumeB': ["P09 (carregar imagens) é repetível: as imagens são conferidas pela etiqueta do release. Retomar continua em P09 com o mesmo plano {p}. Nenhuma Instância foi criada ainda.","P09 (load images) is repeatable: images are checked by the release tag. Resuming continues at P09 with the same plan {p}. No Instance has been created yet.","P09 (charger les images) est répétable : les images sont vérifiées par l’étiquette de version. La reprise continue à P09 avec le même plan {p}. Aucune Instance n’a encore été créée."],
  'inc.removeNote': ['Remover apaga só os caminhos que o diário diz que esta instalação criou: /srv/ocinye e /etc/ocinye. Nenhuma Instância nem dados existem ainda.', 'Removing deletes only the paths the journal says this installation created: /srv/ocinye and /etc/ocinye. No Instance or data exist yet.', 'La suppression efface uniquement les chemins que le journal attribue à cette installation : /srv/ocinye et /etc/ocinye. Aucune Instance ni donnée n’existe encore.'],

  // ── I07 hardware
  'hw.title': ['Hardware e computação', 'Hardware & compute', 'Matériel et calcul'],
  'hw.lead': ['O que o servidor tem, lido sem alterar nada. É informação: só os mínimos da verificação prévia podem impedir a instalação.', 'What the server has, read without changing anything. It is information: only the preflight minimums can prevent installation.', 'Ce dont dispose le serveur, lu sans rien modifier. C’est une information : seuls les minimums de la vérification préalable peuvent empêcher l’installation.'],
  'hw.cpu': ['PROCESSADOR', 'PROCESSOR', 'PROCESSEUR'],
  'hw.mem': ['MEMÓRIA', 'MEMORY', 'MÉMOIRE'],
  'hw.storage': ['ARMAZENAMENTO', 'STORAGE', 'STOCKAGE'],
  'hw.net': ['REDE', 'NETWORK', 'RÉSEAU'],
  'hw.cores': ['{c} núcleos · {t} threads · {a}', '{c} cores · {t} threads · {a}', '{c} cœurs · {t} threads · {a}'],
  'hw.memS': ['total · {f} livres agora', 'total · {f} free now', 'total · {f} libres maintenant'],
  'hw.storageV': ['{v} disponíveis', '{v} available', '{v} disponibles'],
  'hw.storageS': ['em /srv · {fs}', 'in /srv · {fs}', 'dans /srv · {fs}'],
  'hw.netS': ['{n} · IPv4 e IPv6', '{n} · IPv4 and IPv6', '{n} · IPv4 et IPv6'],
  'hw.gpus': ['Aceleradores', 'Accelerators', 'Accélérateurs'],
  'hw.gpuCount': ['{n} GPU detectadas', '{n} GPUs detected', '{n} GPU détectés'],
  'hw.gpuOne': ['1 GPU detectada', '1 GPU detected', '1 GPU détecté'],
  'hw.th.device': ['DISPOSITIVO', 'DEVICE', 'PÉRIPHÉRIQUE'],
  'hw.th.vendor': ['FABRICANTE', 'VENDOR', 'FABRICANT'],
  'hw.th.vram': ['VRAM', 'VRAM', 'VRAM'],
  'hw.th.driver': ['CONTROLADOR', 'DRIVER', 'PILOTE'],
  'hw.th.runtime': ['RUNTIME DE ACELERAÇÃO', 'ACCELERATION RUNTIME', 'RUNTIME D’ACCÉLÉRATION'],
  'hw.th.cap': ['CAPACIDADE', 'CAPABILITY', 'CAPACITÉ'],
  'hw.noGpuT': ['Nenhuma GPU compatível detectada', 'No compatible GPU detected', 'Aucun GPU compatible détecté'],
  'hw.noGpuB': ['Ocinye OS pode ser instalado normalmente sem GPU.', 'Ocinye OS can be installed normally without a GPU.', 'Ocinye OS peut être installé normalement sans GPU.'],
  'hw.cpuOnlyB': ['Não há dispositivos de visualização nem aceleradores no bus PCI. A IA da Instância começa indisponível, que é o estado normal até alguém ligar um nó ou registar um fornecedor.', 'There are no display devices or accelerators on the PCI bus. The Instance’s AI starts unavailable, the normal state until someone connects a node or registers a provider.', 'Aucun périphérique d’affichage ni accélérateur sur le bus PCI. L’IA de l’Instance démarre indisponible, l’état normal jusqu’à ce que quelqu’un connecte un nœud ou enregistre un fournisseur.'],
  'hw.noGpuDisplay': ['Só um controlador de vídeo básico ({m}), que não é um acelerador de computação.', 'Only a basic display controller ({m}), which is not a compute accelerator.', 'Seulement un contrôleur vidéo de base ({m}), qui n’est pas un accélérateur de calcul.'],
  'hw.rtUnavailT': ['GPU visível, runtime de aceleração indisponível', 'GPU visible, acceleration runtime unavailable', 'GPU visible, runtime d’accélération indisponible'],
  'hw.rtUnavailB': ['O controlador {d} está carregado, mas o Docker não tem o runtime de contentores da NVIDIA. A instalação base continua normalmente: nenhuma parte do Ocinye OS instalada agora precisa de GPU.', 'Driver {d} is loaded, but Docker has no NVIDIA container runtime. The base installation continues normally: no part of Ocinye OS installed now needs a GPU.', 'Le pilote {d} est chargé, mais Docker n’a pas le runtime de conteneurs NVIDIA. L’installation de base continue normalement : aucune partie d’Ocinye OS installée maintenant n’a besoin d’un GPU.'],
  'hw.errT': ['Não foi possível ler os aceleradores', 'Accelerators could not be read', 'Les accélérateurs n’ont pas pu être lus'],
  'hw.errB': ['A leitura de /sys/bus/pci foi recusada ({c}). Processador, memória e armazenamento foram lidos; a instalação base não depende de GPU e pode continuar. O relatório regista «desconhecido», nunca «sem GPU».', 'Reading /sys/bus/pci was refused ({c}). Processor, memory and storage were read; the base installation does not depend on a GPU and can continue. The report records “unknown”, never “no GPU”.', 'La lecture de /sys/bus/pci a été refusée ({c}). Processeur, mémoire et stockage ont été lus ; l’installation de base ne dépend pas d’un GPU et peut continuer. Le rapport indique « inconnu », jamais « sans GPU ».'],
  'hw.rt.nvidia': ['NVIDIA Container Toolkit', 'NVIDIA Container Toolkit', 'NVIDIA Container Toolkit'],
  'hw.rt.missing': ['ausente no Docker', 'missing in Docker', 'absent de Docker'],
  'hw.rt.rocm': ['ROCm (/dev/kfd)', 'ROCm (/dev/kfd)', 'ROCm (/dev/kfd)'],
  'hw.cc': ['Computação confidencial', 'Confidential computing', 'Calcul confidentiel'],
  'hw.ccV': ['SEV-SNP anunciado pelo processador · DETECTADO, não verificado nem atestado', 'SEV-SNP advertised by the processor · DETECTED, not verified or attested', 'SEV-SNP annoncé par le processeur · DÉTECTÉ, ni vérifié ni attesté'],
  'hw.ccNone': ['Nenhuma capacidade anunciada', 'No capability advertised', 'Aucune capacité annoncée'],
  'hw.tpm': ['TPM', 'TPM', 'TPM'],
  'hw.tpmV': ['/dev/tpmrm0 presente · DETECTADO', '/dev/tpmrm0 present · DETECTED', '/dev/tpmrm0 présent · DÉTECTÉ'],
  'hw.readiness': ['Prontidão para Ocinye Compute', 'Ocinye Compute readiness', 'Préparation à Ocinye Compute'],
  'hw.ready.gpu': ['GPU detectada; Provider Mode ainda não configurado', 'GPU detected; Provider Mode not configured yet', 'GPU détecté ; Provider Mode pas encore configuré'],
  'hw.ready.cpu': ['Hardware compatível com futuras capacidades Ocinye Compute (só CPU)', 'Hardware compatible with future Ocinye Compute capabilities (CPU only)', 'Matériel compatible avec les futures capacités Ocinye Compute (CPU uniquement)'],
  'hw.ready.rt': ['GPU detectada; runtime de aceleração em falta para uso futuro', 'GPU detected; acceleration runtime missing for future use', 'GPU détecté ; runtime d’accélération manquant pour un usage futur'],
  'hw.ready.unknown': ['Não avaliada: os aceleradores não foram lidos', 'Not assessed: accelerators were not read', 'Non évaluée : les accélérateurs n’ont pas été lus'],
  'cn.k': ['OCINYE COMPUTE NETWORK · FUTURO · NÃO IMPLEMENTADO NA D011', 'OCINYE COMPUTE NETWORK · FUTURE · NOT IMPLEMENTED IN D011', 'OCINYE COMPUTE NETWORK · FUTUR · NON IMPLÉMENTÉ DANS D011'],
  'cn.t': ['Ocinye Compute Network', 'Ocinye Compute Network', 'Ocinye Compute Network'],
  'cn.b': ['Este sistema poderá ser configurado posteriormente como um Ocinye Compute Node para disponibilizar recursos computacionais a workloads compatíveis. Instalar o Ocinye OS não inscreve este servidor em rede nenhuma.', 'This system may later be configured as an Ocinye Compute Node to make compute resources available to compatible workloads. Installing Ocinye OS does not enrol this server in any network.', 'Ce système pourra être configuré ultérieurement comme Ocinye Compute Node pour mettre des ressources de calcul à disposition de workloads compatibles. Installer Ocinye OS n’inscrit ce serveur dans aucun réseau.'],
  'cn.state': ['Estado', 'State', 'État'],
  'cn.later': ['Configurar depois · numa versão futura', 'Configure later · in a future version', 'Configurer plus tard · dans une version future'],
  'cn.provider': ['Provider Mode', 'Provider Mode', 'Provider Mode'],
  'cn.off': ['Desligado', 'Off', 'Désactivé'],

  // ── I08 instância
  'inst.title': ['Instância', 'Instance', 'Instance'],
  'inst.lead': ['Uma instalação tem uma Instância: o ambiente governado onde vivem membros, dados e políticas. O Core cria-a no primeiro arranque.', 'An installation has one Instance: the governed environment where members, data and policies live. The Core creates it on first start.', 'Une installation a une Instance : l’environnement gouverné où vivent membres, données et politiques. Le Core la crée au premier démarrage.'],
  'inst.name': ['Nome da Instância', 'Instance name', 'Nom de l’Instance'],
  'inst.nameHint': ['O nome que as pessoas lêem. Pode mudar-se depois em Administração.', 'The name people read. It can be changed later in Administration.', 'Le nom que les personnes lisent. Il peut être modifié plus tard dans Administration.'],
  'inst.slug': ['Identificador técnico', 'Technical identifier', 'Identifiant technique'],
  'inst.slugHint': ['Derivado do nome pelo Core; não se renomeia. Valores de exemplo como «test» ou «demo» são recusados.', 'Derived from the name by the Core; it is never renamed. Example values such as “test” or “demo” are refused.', 'Dérivé du nom par le Core ; il n’est jamais renommé. Les valeurs d’exemple comme « test » ou « demo » sont refusées.'],
  'inst.locale': ['Idioma e fuso horário', 'Language and time zone', 'Langue et fuseau horaire'],
  'inst.localeV': ['Escolhem-se depois da instalação, por cada membro e em Administração. A instalação não os fixa.', 'Chosen after installation, by each member and in Administration. The installation does not set them.', 'Choisis après l’installation, par chaque membre et dans Administration. L’installation ne les fixe pas.'],

  // ── I09 distribuições
  'dist.title': ['Distribuições activadas', 'Enabled Distributions', 'Distributions activées'],
  'dist.lead': ['Escolha uma ou mais. A primeira escolhida é a Distribuição com que a Instância nasce; as outras activam-se com ela. Activar uma Distribuição não dá acesso a ninguém nem concede papéis.', 'Choose one or more. The first chosen is the Distribution the Instance is born with; the others are enabled with it. Enabling a Distribution gives no one access and grants no roles.', 'Choisissez-en une ou plusieurs. La première choisie est la Distribution avec laquelle l’Instance naît ; les autres sont activées avec elle. Activer une Distribution ne donne accès à personne et n’accorde aucun rôle.'],
  'dist.research': ['Research', 'Research', 'Research'],
  'dist.business': ['Business', 'Business', 'Business'],
  'dist.personal': ['Personal', 'Personal', 'Personal'],
  'dist.education': ['Education', 'Education', 'Education'],
  'dist.researchD': ['Projectos, ideias, dados, resultados e conhecimento científico.', 'Projects, ideas, data, results and scientific knowledge.', 'Projets, idées, données, résultats et connaissances scientifiques.'],
  'dist.businessD': ['Trabalho de equipa, correio, calendário e ficheiros da organização.', 'Teamwork, mail, calendar and organisation files.', 'Travail d’équipe, courrier, calendrier et fichiers de l’organisation.'],
  'dist.personalD': ['Espaço próprio: notas, ficheiros e calendário pessoais.', 'Own space: personal notes, files and calendar.', 'Espace propre : notes, fichiers et calendrier personnels.'],
  'dist.educationD': ['Ensino e aprendizagem: cursos, materiais e turmas.', 'Teaching and learning: courses, materials and classes.', 'Enseignement et apprentissage : cours, supports et classes.'],
  'dist.first': ['PRIMEIRA', 'FIRST', 'PREMIÈRE'],
  'dist.count': ['{n} de 4 activadas', '{n} of 4 enabled', '{n} sur 4 activées'],
  'dist.noneErr': ['Escolha pelo menos uma Distribuição.', 'Choose at least one Distribution.', 'Choisissez au moins une Distribution.'],
  'dist.admin': ['O primeiro administrador recebe acesso a todas as activadas. Os outros membros recebem acesso em Administração.', 'The first administrator receives access to all enabled ones. Other members receive access in Administration.', 'Le premier administrateur reçoit l’accès à toutes celles activées. Les autres membres reçoivent l’accès dans Administration.'],

  // ── I10 pontos de acesso
  'ep.title': ['Pontos de acesso', 'Access endpoints', 'Points d’accès'],
  'ep.lead': ['Os endereços por onde as pessoas entram no Ocinye OS. Não são o servidor SSH: o servidor é {s}. Um ponto pode fixar uma Distribuição; a ligação é sempre explícita, nunca deduzida do nome.', 'The addresses people use to enter Ocinye OS. They are not the SSH server: the server is {s}. An endpoint may pin a Distribution; the binding is always explicit, never inferred from the name.', 'Les adresses par lesquelles les personnes entrent dans Ocinye OS. Ce ne sont pas le serveur SSH : le serveur est {s}. Un point peut fixer une Distribution ; le lien est toujours explicite, jamais déduit du nom.'],
  'ep.th.host': ['ENDEREÇO', 'ADDRESS', 'ADRESSE'],
  'ep.th.binding': ['DESTINO', 'DESTINATION', 'DESTINATION'],
  'ep.th.dns': ['DNS', 'DNS', 'DNS'],
  'ep.generic': ['Instância · Distribuição escolhida depois da entrada', 'Instance · Distribution chosen after sign-in', 'Instance · Distribution choisie après la connexion'],
  'ep.canonical': ['CANÓNICO', 'CANONICAL', 'CANONIQUE'],
  'ep.bound': ['Fixo em {d}', 'Pinned to {d}', 'Fixé sur {d}'],
  'ep.dnsT': ['Registos DNS necessários', 'Required DNS records', 'Enregistrements DNS requis'],
  'ep.dnsB': ['Crie estes registos no fornecedor do seu domínio. O instalador não altera DNS; verifica a partir deste computador.', 'Create these records at your domain provider. The installer does not change DNS; it checks from this computer.', 'Créez ces enregistrements chez le fournisseur de votre domaine. L’installateur ne modifie pas le DNS ; il vérifie depuis cet ordinateur.'],
  'ep.th.type': ['TIPO', 'TYPE', 'TYPE'],
  'ep.th.value': ['VALOR ESPERADO', 'EXPECTED VALUE', 'VALEUR ATTENDUE'],
  'ep.th.seen': ['OBSERVADO', 'OBSERVED', 'OBSERVÉ'],
  'ep.dnsPendT': ['DNS ainda não aponta para o servidor', 'DNS does not point to the server yet', 'Le DNS ne pointe pas encore vers le serveur'],
  'ep.dnsPendB': ['Pode instalar na mesma: a instalação verifica-se dentro do servidor. «Abrir Ocinye OS» só fica disponível quando todos os endereços resolverem para {ip}. A propagação pode levar algum tempo.', 'You can install anyway: installation is verified inside the server. “Open Ocinye OS” only becomes available when every address resolves to {ip}. Propagation may take some time.', 'Vous pouvez quand même installer : l’installation est vérifiée à l’intérieur du serveur. « Ouvrir Ocinye OS » n’est disponible que lorsque toutes les adresses résolvent vers {ip}. La propagation peut prendre du temps.'],
  'ep.dnsWrongT': ['Um endereço aponta para outro servidor', 'An address points to another server', 'Une adresse pointe vers un autre serveur'],
  'ep.dnsWrongB': ['{h} resolve para {o}, não para {ip}. Corrija o registo A no fornecedor do domínio.', '{h} resolves to {o}, not {ip}. Fix the A record at your domain provider.', '{h} résout vers {o}, et non {ip}. Corrigez l’enregistrement A chez le fournisseur du domaine.'],
  'ep.hint': ['Os nomes têm de ser seus. Não é preciso nenhum endereço ocinye.com.', 'The names must be yours. No ocinye.com address is required.', 'Les noms doivent vous appartenir. Aucune adresse ocinye.com n’est requise.'],
  'ep.noneDist': ['Nenhuma (genérico)', 'None (generic)', 'Aucune (générique)'],

  // ── I11 TLS
  'tls.title': ['Certificado TLS', 'TLS certificate', 'Certificat TLS'],
  'tls.lead': ['O Workspace só funciona em HTTPS. Para uso real, forneça um certificado que cubra todos os pontos de acesso.', 'The Workspace only works over HTTPS. For real use, provide a certificate covering every access endpoint.', 'Le Workspace ne fonctionne qu’en HTTPS. En usage réel, fournissez un certificat couvrant tous les points d’accès.'],
  'tls.provided': ['Certificado fornecido por si', 'Certificate you provide', 'Certificat fourni par vous'],
  'tls.providedD': ['Certificado, chave privada e cadeia opcional, em PEM. Recomendado para qualquer uso real.', 'Certificate, private key and optional chain, in PEM. Recommended for any real use.', 'Certificat, clé privée et chaîne facultative, en PEM. Recommandé pour tout usage réel.'],
  'tls.self': ['Certificado auto-assinado', 'Self-signed certificate', 'Certificat auto-signé'],
  'tls.selfD': ['Gerado no servidor para os pontos de acesso. Os browsers não confiam nele: não serve uso normal em produção pública.', 'Generated on the server for the access endpoints. Browsers do not trust it: not for normal public production use.', 'Généré sur le serveur pour les points d’accès. Les navigateurs ne lui font pas confiance : ne convient pas à un usage normal en production publique.'],
  'tls.acme': ['Emissão automática (ACME) não existe nesta versão.', 'Automatic issuance (ACME) does not exist in this version.', 'L’émission automatique (ACME) n’existe pas dans cette version.'],
  'tls.cert': ['Certificado', 'Certificate', 'Certificat'],
  'tls.key': ['Chave privada', 'Private key', 'Clé privée'],
  'tls.chain': ['Cadeia intermédia', 'Intermediate chain', 'Chaîne intermédiaire'],
  'tls.optional': ['opcional', 'optional', 'facultatif'],
  'tls.empty': ['Nenhum ficheiro escolhido', 'No file chosen', 'Aucun fichier choisi'],
  'tls.keyNote': ['O conteúdo da chave nunca é mostrado. É enviada ao servidor pela ligação SSH e escrita com permissões 0600.', 'The key contents are never shown. It is sent to the server over the SSH connection and written with 0600 permissions.', 'Le contenu de la clé n’est jamais affiché. Elle est envoyée au serveur par la connexion SSH et écrite avec les permissions 0600.'],
  'tls.checks': ['Validação neste computador', 'Validation on this computer', 'Validation sur cet ordinateur'],
  'tls.c.parse': ['Lê-se como certificado X.509 em PEM', 'Parses as a PEM X.509 certificate', 'Se lit comme certificat X.509 en PEM'],
  'tls.c.match': ['A chave privada corresponde ao certificado', 'The private key matches the certificate', 'La clé privée correspond au certificat'],
  'tls.c.exp': ['Válido até {d}', 'Valid until {d}', 'Valide jusqu’au {d}'],
  'tls.c.names': ['Cobre {h}', 'Covers {h}', 'Couvre {h}'],
  'tls.c.chain': ['Cadeia completa até uma raiz conhecida', 'Complete chain to a known root', 'Chaîne complète jusqu’à une racine connue'],
  'tls.c.matchFail': ['A chave privada não corresponde a este certificado', 'The private key does not match this certificate', 'La clé privée ne correspond pas à ce certificat'],
  'tls.c.namesFail': ['Não cobre {h}', 'Does not cover {h}', 'Ne couvre pas {h}'],
  'tls.invalidT': ['O certificado não serve esta instalação', 'The certificate does not fit this installation', 'Le certificat ne convient pas à cette installation'],
  'tls.invalidB': ['Corrija os ficheiros antes de continuar. A instalação não começa com material TLS inválido.', 'Fix the files before continuing. Installation does not start with invalid TLS material.', 'Corrigez les fichiers avant de continuer. L’installation ne démarre pas avec un matériel TLS invalide.'],
  'tls.selfAlertT': ['Só para teste e desenvolvimento', 'Test and development only', 'Test et développement uniquement'],
  'tls.selfAlertB': ['Não é de confiança para uso público normal em produção. Os browsers mostram um aviso e o relatório regista o modo de teste. Substitua-o por um certificado seu antes de servir pessoas.', 'Not trusted for normal public production use. Browsers show a warning and the report records test mode. Replace it with your own certificate before serving people.', 'Non fiable pour un usage public normal en production. Les navigateurs affichent un avertissement et le rapport indique le mode test. Remplacez-le par votre propre certificat avant de servir des personnes.'],

  // ── I12 administrador
  'adm.title': ['Primeiro administrador', 'First administrator', 'Premier administrateur'],
  'adm.lead': ['O Core cria duas identidades ligadas: a pessoa que responde pela Instância e a identidade privilegiada com que administra. O instalador não escolhe palavras-passe.', 'The Core creates two linked identities: the person accountable for the Instance and the privileged identity they administer with. The installer chooses no passwords.', 'Le Core crée deux identités liées : la personne responsable de l’Instance et l’identité privilégiée avec laquelle elle administre. L’installateur ne choisit aucun mot de passe.'],
  'adm.person': ['Pessoa institucional', 'Institutional person', 'Personne institutionnelle'],
  'adm.personD': ['Quem responde. Nasce sem credencial; o acesso dá-se depois, em Administração.', 'Who is accountable. Created without a credential; access is given later, in Administration.', 'Qui est responsable. Créée sans identifiant ; l’accès est donné plus tard, dans Administration.'],
  'adm.priv': ['Identidade privilegiada', 'Privileged identity', 'Identité privilégiée'],
  'adm.privD': ['Executa com autoridade de plataforma. Recebe uma credencial temporária de uso único.', 'Acts with platform authority. Receives a single-use temporary credential.', 'Agit avec l’autorité de plateforme. Reçoit un identifiant temporaire à usage unique.'],
  'adm.name': ['Nome completo', 'Full name', 'Nom complet'],
  'adm.email': ['Endereço de correio', 'Email address', 'Adresse e-mail'],
  'adm.after': ['Depois da instalação', 'After installation', 'Après l’installation'],
  'adm.afterV': ['A credencial temporária é mostrada uma vez no fim. No primeiro acesso pelo browser define-se a palavra-passe definitiva e enrola-se o segundo factor, obrigatório para identidades privilegiadas, com os códigos de recuperação. Nada disso acontece no instalador.', 'The temporary credential is shown once at the end. On first browser access the permanent password is set and the second factor, mandatory for privileged identities, is enrolled with recovery codes. None of that happens in the installer.', 'L’identifiant temporaire est affiché une fois à la fin. Au premier accès par le navigateur, on définit le mot de passe définitif et on enrôle le second facteur, obligatoire pour les identités privilégiées, avec les codes de récupération. Rien de cela ne se passe dans l’installateur.'],
  'adm.distinctErr': ['A pessoa e a identidade privilegiada têm de ter endereços diferentes.', 'The person and the privileged identity must have different addresses.', 'La personne et l’identité privilégiée doivent avoir des adresses différentes.'],

  // ── I13 revisão
  'rev.title': ['Rever o plano de instalação', 'Review the installation plan', 'Revoir le plan d’installation'],
  'rev.lead': ['Isto é tudo o que vai acontecer no servidor. Ao instalar, o plano fica fixo; mudar alguma coisa depois cria um plano novo.', 'This is everything that will happen on the server. When you install, the plan is locked; changing anything afterwards creates a new plan.', 'Voici tout ce qui va se passer sur le serveur. À l’installation, le plan est figé ; modifier quoi que ce soit ensuite crée un nouveau plan.'],
  'rev.plan': ['Plano', 'Plan', 'Plan'],
  'rev.hash': ['soma', 'hash', 'somme'],
  'rev.release': ['Release', 'Release', 'Version'],
  'rev.server': ['Servidor', 'Server', 'Serveur'],
  'rev.hardware': ['Hardware', 'Hardware', 'Matériel'],
  'rev.instance': ['Instância e Distribuições', 'Instance and Distributions', 'Instance et Distributions'],
  'rev.endpoints': ['Pontos de acesso e TLS', 'Access endpoints and TLS', 'Points d’accès et TLS'],
  'rev.admin': ['Primeiro administrador', 'First administrator', 'Premier administrateur'],
  'rev.changes': ['Alterações no servidor', 'Changes on the server', 'Modifications sur le serveur'],
  'rev.ch1': ['Cria /srv/ocinye (release, spool de conversão, backups) e /etc/ocinye (configuração e segredos gerados no servidor, 0600)', 'Creates /srv/ocinye (release, conversion spool, backups) and /etc/ocinye (configuration and secrets generated on the server, 0600)', 'Crée /srv/ocinye (version, file de conversion, sauvegardes) et /etc/ocinye (configuration et secrets générés sur le serveur, 0600)'],
  'rev.ch2': ['Carrega 5 imagens do release no Docker e descarrega PostgreSQL, Redis, Garage e nginx', 'Loads 5 release images into Docker and pulls PostgreSQL, Redis, Garage and nginx', 'Charge 5 images de la version dans Docker et télécharge PostgreSQL, Redis, Garage et nginx'],
  'rev.ch3': ['Cria a base de dados e aplica {n} migrações; cria o armazenamento de objectos privado', 'Creates the database and applies {n} migrations; creates the private object store', 'Crée la base de données et applique {n} migrations ; crée le stockage d’objets privé'],
  'rev.ch4': ['Configura nginx nas portas 80 e 443 para os pontos de acesso; instala o certificado', 'Configures nginx on ports 80 and 443 for the access endpoints; installs the certificate', 'Configure nginx sur les ports 80 et 443 pour les points d’accès ; installe le certificat'],
  'rev.ch5': ['Instala e activa ocinye.service (systemd) para arrancar depois de um reboot', 'Installs and enables ocinye.service (systemd) to start after a reboot', 'Installe et active ocinye.service (systemd) pour démarrer après un redémarrage'],
  'rev.ch6': ["Não altera SSH, sudo, nem regras de firewall que não sejam do Ocinye. Nunca desactiva a firewall.","Does not change SSH, sudo, or firewall rules that are not Ocinye’s. Never disables the firewall.","Ne modifie ni SSH, ni sudo, ni les règles de pare-feu qui ne sont pas d’Ocinye. Ne désactive jamais le pare-feu."],
  'rev.ch7': ['Envia um executor temporário (ocinye-bootstrap) que é removido no fim; fica só o diário de instalação, sem segredos', 'Sends a temporary executor (ocinye-bootstrap) that is removed at the end; only the installation journal remains, without secrets', 'Envoie un exécuteur temporaire (ocinye-bootstrap) supprimé à la fin ; seul le journal d’installation reste, sans secrets'],
  'rev.provider': ['Provider Mode: desligado. Nenhuma inscrição em rede de computação.', 'Provider Mode: off. No compute network enrolment.', 'Provider Mode : désactivé. Aucune inscription à un réseau de calcul.'],
  'rev.sealing': ['A raiz de selagem é gerada no servidor. Sem ela um backup não se lê: guarde-a fora do servidor depois de instalar.', 'The sealing root is generated on the server. Without it a backup cannot be read: keep it off the server after installing.', 'La racine de scellement est générée sur le serveur. Sans elle, une sauvegarde est illisible : conservez-la hors du serveur après l’installation.'],
  'rev.duration': ['Duração habitual: 2 a 5 minutos, mais o tempo de transferência.', 'Usual duration: 2 to 5 minutes, plus transfer time.', 'Durée habituelle : 2 à 5 minutes, plus le temps de transfert.'],

  // ── I14 instalação
  'ins.title': ['A instalar o Ocinye OS', 'Installing Ocinye OS', 'Installation d’Ocinye OS'],
  'ins.lead': ['Pode deixar o instalador aberto. Se a ligação cair, a instalação continua no servidor e o instalador volta a ligar-se ao diário.', 'You can leave the installer open. If the connection drops, installation continues on the server and the installer reconnects to the journal.', 'Vous pouvez laisser l’installateur ouvert. Si la connexion tombe, l’installation continue sur le serveur et l’installateur se reconnecte au journal.'],
  'ins.overall': ["Fase {n} de 16 · {p}","Phase {n} of 16 · {p}","Phase {n} sur 16 · {p}"],
  'ins.elapsed': ['decorrido {t}', '{t} elapsed', '{t} écoulé'],
  'ins.pnr': ['A PARTIR DAQUI HÁ SEGREDOS NO SERVIDOR · PARAR LEVA A UM ESTADO RECUPERÁVEL, NÃO A UM SERVIDOR LIMPO', 'FROM HERE ON SECRETS EXIST ON THE SERVER · STOPPING LEADS TO A RECOVERABLE STATE, NOT A CLEAN SERVER', 'À PARTIR D’ICI DES SECRETS EXISTENT SUR LE SERVEUR · ARRÊTER MÈNE À UN ÉTAT RÉCUPÉRABLE, PAS À UN SERVEUR PROPRE'],
  'ins.warnings': ['{n} aviso', '{n} warning', '{n} avertissement'],
  'ph.P01': ["Preparar o servidor","Prepare the server","Préparer le serveur"],
  'ph.P02': ["Transferir o release","Transfer the release","Transférer la version"],
  'ph.P03': ["Confirmar a verificação prévia","Confirm the preflight","Confirmer la vérification préalable"],
  'ph.P04': ["Instalar pré-requisitos","Install prerequisites","Installer les prérequis"],
  'ph.P05': ["Instalar o release","Install the release","Installer la version"],
  'ph.P06': ["Gerar configuração e segredos","Generate configuration and secrets","Générer configuration et secrets"],
  'ph.P07': ["Configurar proxy e TLS","Configure proxy and TLS","Configurer proxy et TLS"],
  'ph.P08': ["Regras de firewall do Ocinye","Ocinye firewall rules","Règles de pare-feu Ocinye"],
  'ph.P09': ["Carregar imagens","Load images","Charger les images"],
  'ph.P10': ["Base de dados e armazenamento","Database and storage","Base de données et stockage"],
  'ph.P11': ["Instância, migrações e administrador","Instance, migrations and administrator","Instance, migrations et administrateur"],
  'ph.P12': ["Pontos de acesso","Access endpoints","Points d’accès"],
  'ph.P13': ["Arrancar serviços","Start services","Démarrer les services"],
  'ph.P14': ["Arranque automático (systemd)","Automatic start (systemd)","Démarrage automatique (systemd)"],
  'op.P01': ['ocinye-bootstrap enviado e conferido (SHA-256)', 'ocinye-bootstrap sent and checked (SHA-256)', 'ocinye-bootstrap envoyé et vérifié (SHA-256)'],
  'op.P02': ['{a} de {b} · somas conferidas no servidor', '{a} of {b} · sums checked on the server', '{a} sur {b} · sommes vérifiées sur le serveur'],
  'op.P07': ['a carregar ocinye-worker ({n} de 5)', 'loading ocinye-worker ({n} of 5)', 'chargement de ocinye-worker ({n} sur 5)'],
  'op.P09': ['a aplicar migração 0041 de 0064', 'applying migration 0041 of 0064', 'application de la migration 0041 sur 0064'],
  'ev.time': ['HORA', 'TIME', 'HEURE'],
  'ev.phase': ['FASE', 'PHASE', 'PHASE'],
  'ev.event': ['EVENTO', 'EVENT', 'ÉVÉNEMENT'],
  'ev.detail': ['DETALHE', 'DETAIL', 'DÉTAIL'],
  'ev.redacted': ['[segredo omitido]', '[secret omitted]', '[secret omis]'],
  'ins.warnImg': ['A transferência de nginx:1.27-alpine demorou 48 s; ligação lenta ao registry', 'Pulling nginx:1.27-alpine took 48 s; slow connection to the registry', 'Le téléchargement de nginx:1.27-alpine a pris 48 s ; connexion lente au registre'],
  'cancel.title': ['A aguardar um ponto seguro para interromper…', 'Waiting for a safe point to stop…', 'En attente d’un point sûr pour interrompre…'],
  'cancel.body': ["P11 está a aplicar migrações dentro de uma transacção. A instalação pára quando P11 terminar, e o diário fica em PARADA, pronto para retomar ou remover. Fechar o instalador não interrompe o servidor.","P11 is applying migrations inside a transaction. Installation stops when P11 finishes, and the journal is left STOPPED, ready to resume or remove. Closing the installer does not interrupt the server.","P11 applique des migrations dans une transaction. L’installation s’arrête lorsque P11 se termine, et le journal reste ARRÊTÉ, prêt à reprendre ou à supprimer. Fermer l’installateur n’interrompt pas le serveur."],
  'cancel.keep': ['Continuar a instalação', 'Keep installing', 'Poursuivre l’installation'],

  // ── interrupção
  'int.title': ['A ligação ao servidor caiu', 'The connection to the server dropped', 'La connexion au serveur est tombée'],
  'int.lead': ['O executor no servidor continua a instalação sozinho e escreve o diário. Voltar a ligar lê o diário e mostra onde está.', 'The executor on the server continues installing on its own and writes the journal. Reconnecting reads the journal and shows where it is.', 'L’exécuteur sur le serveur poursuit l’installation seul et écrit le journal. Se reconnecter lit le journal et montre où il en est.'],
  'int.last': ['Último estado conhecido', 'Last known state', 'Dernier état connu'],
  'int.lastV': ["P09 Carregar imagens · a decorrer · {t}","P09 Load images · running · {t}","P09 Charger les images · en cours · {t}"],
  'int.trying': ['A tentar de novo em {s} s (tentativa {n})', 'Retrying in {s} s (attempt {n})', 'Nouvelle tentative dans {s} s (tentative {n})'],
  'int.unknown': ['O resultado das fases em curso só se sabe depois de voltar a ligar. O instalador não mostra sucesso sem o diário o confirmar.', 'The result of running phases is only known after reconnecting. The installer shows no success without the journal confirming it.', 'Le résultat des phases en cours n’est connu qu’après reconnexion. L’installateur n’affiche aucun succès sans confirmation du journal.'],

  // ── falhas
  'fail.title': ['A instalação falhou', 'Installation failed', 'L’installation a échoué'],
  'fail.phase': ['Fase', 'Phase', 'Phase'],
  'fail.reason': ['Razão', 'Reason', 'Raison'],
  'fail.code': ['Código', 'Code', 'Code'],
  'fail.next': ['O que fazer', 'What to do', 'Que faire'],
  'fail.notOp': ['O Ocinye OS não está operacional neste servidor.', 'Ocinye OS is not operational on this server.', 'Ocinye OS n’est pas opérationnel sur ce serveur.'],
  'fail.journal': ['O diário de instalação ficou no servidor em /var/lib/ocinye-installer/{id}.json e no relatório local. Não contém segredos.', 'The installation journal remains on the server at /var/lib/ocinye-installer/{id}.json and in the local report. It contains no secrets.', 'Le journal d’installation reste sur le serveur dans /var/lib/ocinye-installer/{id}.json et dans le rapport local. Il ne contient aucun secret.'],
  'fail.migT': ["P11 · uma migração falhou","P11 · a migration failed","P11 · une migration a échoué"],
  'fail.migR': ['A migração 0041 foi recusada pela base de dados. A transacção foi revertida: a base ficou na versão 0040.', 'Migration 0041 was refused by the database. The transaction was rolled back: the database stayed at version 0040.', 'La migration 0041 a été refusée par la base de données. La transaction a été annulée : la base est restée en version 0040.'],
  'fail.migN': ['Não é repetível com o mesmo release: o mesmo pacote falharia igual. Guarde o relatório e envie-o a quem mantém o Ocinye OS. Depois, remova a instalação incompleta (nenhuma Instância foi criada) e instale um release corrigido.', 'Not retryable with the same release: the same package would fail the same way. Save the report and send it to the Ocinye OS maintainers. Then remove the incomplete installation (no Instance was created) and install a fixed release.', 'Non répétable avec la même version : le même paquet échouerait de la même façon. Enregistrez le rapport et envoyez-le aux mainteneurs d’Ocinye OS. Ensuite, supprimez l’installation incomplète (aucune Instance n’a été créée) et installez une version corrigée.'],
  'fail.xferT': ["P02 · a transferência falhou","P02 · the transfer failed","P02 · le transfert a échoué"],
  'fail.xferR': ['images/ocinye-core-server.tar chegou com uma soma diferente da do pacote. O ficheiro no servidor foi apagado; nada foi instalado.', 'images/ocinye-core-server.tar arrived with a sum different from the package. The file on the server was deleted; nothing was installed.', 'images/ocinye-core-server.tar est arrivé avec une somme différente de celle du paquet. Le fichier sur le serveur a été supprimé ; rien n’a été installé.'],
  'fail.xferN': ['Repetível: a transferência recomeça a partir dos ficheiros que já conferem.', 'Retryable: the transfer restarts from the files that already match.', 'Répétable : le transfert reprend à partir des fichiers qui correspondent déjà.'],
  'fail.svcT': ["P13 · o serviço core não ficou saudável","P13 · the core service did not become healthy","P13 · le service core n’est pas devenu sain"],
  'fail.svcR': ['ocinye-core-1 continuou «starting» durante 300 s. O registo do serviço diz: «ligação à base de dados recusada».', 'ocinye-core-1 stayed “starting” for 300 s. The service log says: “database connection refused”.', 'ocinye-core-1 est resté « starting » pendant 300 s. Le journal du service indique : « connexion à la base de données refusée ».'],
  'fail.svcN': ['Repetível uma vez: o instalador volta a arrancar os serviços com a mesma configuração. Se falhar outra vez, guarde o relatório.', 'Retryable once: the installer restarts the services with the same configuration. If it fails again, save the report.', 'Répétable une fois : l’installateur redémarre les services avec la même configuration. En cas de nouvel échec, enregistrez le rapport.'],
  'fail.admT': ["P11 · o bootstrap do administrador falhou","P11 · the administrator bootstrap failed","P11 · le bootstrap de l’administrateur a échoué"],
  'fail.admR': ["O Core recusou: «já existe um administrador utilizável». A base não estava vazia quando P11 começou.","The Core refused: “a usable administrator already exists”. The database was not empty when P11 started.","Le Core a refusé : « un administrateur utilisable existe déjà ». La base n’était pas vide au début de P11."],
  'fail.admN': ['Não é repetível: o bootstrap corre uma única vez e não tem opção para forçar. Guarde o relatório; a recuperação de acesso administrativo segue o runbook recover-administrative-access.', 'Not retryable: the bootstrap runs only once and has no override. Save the report; recovering administrative access follows the recover-administrative-access runbook.', 'Non répétable : le bootstrap ne s’exécute qu’une fois et n’a pas d’option de forçage. Enregistrez le rapport ; la récupération de l’accès administratif suit le runbook recover-administrative-access.'],

  // ── I15 verificação
  'ver.title': ['A verificar o Ocinye OS', 'Verifying Ocinye OS', 'Vérification d’Ocinye OS'],
  'ver.lead': ['Contentores a correr não provam que o Ocinye OS funciona. Estas verificações perguntam ao próprio produto.', 'Running containers do not prove Ocinye OS works. These checks ask the product itself.', 'Des conteneurs en cours d’exécution ne prouvent pas qu’Ocinye OS fonctionne. Ces vérifications interrogent le produit lui-même.'],
  'ver.g.server': ['NO SERVIDOR', 'ON THE SERVER', 'SUR LE SERVEUR'],
  'ver.g.local': ['A PARTIR DESTE COMPUTADOR', 'FROM THIS COMPUTER', 'DEPUIS CET ORDINATEUR'],
  'ver.services': ['Serviços saudáveis', 'Services healthy', 'Services sains'],
  'ver.servicesD': ['core, workspace, worker, proxy, postgres, redis, object-store', 'core, workspace, worker, proxy, postgres, redis, object-store', 'core, workspace, worker, proxy, postgres, redis, object-store'],
  'ver.db': ['Base de dados', 'Database', 'Base de données'],
  'ver.dbD': ['O Core liga-se e lê', 'The Core connects and reads', 'Le Core se connecte et lit'],
  'ver.mig': ['Migrações', 'Migrations', 'Migrations'],
  'ver.migD': ['Esquema 0064 = manifesto do release', 'Schema 0064 = release manifest', 'Schéma 0064 = manifeste de la version'],
  'ver.core': ['Prontidão do Core', 'Core readiness', 'Disponibilité du Core'],
  'ver.coreD': ['/ready responde {s} · contrato v{v}', '/ready answers {s} · contract v{v}', '/ready répond {s} · contrat v{v}'],
  'ver.instance': ['Identidade da Instância', 'Instance identity', 'Identité de l’Instance'],
  'ver.instanceD': ['«{n}» lida do Core', '“{n}” read from the Core', '« {n} » lue depuis le Core'],
  'ver.dists': ['Distribuições activadas', 'Enabled Distributions', 'Distributions activées'],
  'ver.distsD': ['{d} · lidas do Core, não do formulário', '{d} · read from the Core, not the form', '{d} · lues depuis le Core, pas le formulaire'],
  'ver.registry': ['Registo de aplicações', 'Application registry', 'Registre d’applications'],
  'ver.registryD': ['28 aplicações registadas; as da Distribuição activas', '28 registered applications; those of the Distribution active', '28 applications enregistrées ; celles de la Distribution actives'],
  'ver.storage': ['Armazenamento de objectos', 'Object storage', 'Stockage d’objets'],
  'ver.storageD': ['Bucket privado criado e legível pelo Core', 'Private bucket created and readable by the Core', 'Bucket privé créé et lisible par le Core'],
  'ver.dns': ['DNS dos pontos de acesso', 'Access endpoint DNS', 'DNS des points d’accès'],
  'ver.https': ['HTTPS e certificado', 'HTTPS and certificate', 'HTTPS et certificat'],
  'ver.httpsD': ['O certificado servido é o do plano · TLS 1.3', 'The served certificate is the planned one · TLS 1.3', 'Le certificat servi est celui du plan · TLS 1.3'],
  'ver.ep': ['Ponto → Instância', 'Endpoint → Instance', 'Point → Instance'],
  'ver.epD': ['Cada endereço resolve a Instância esperada; business.empresa.test fixa Business', 'Each address resolves the expected Instance; business.empresa.test pins Business', 'Chaque adresse résout l’Instance attendue ; business.empresa.test fixe Business'],
  'ver.login': ['Página de entrada', 'Sign-in page', 'Page de connexion'],
  'ver.loginD': ['https://os.empresa.test/ → 303 → /login → 200', 'https://os.empresa.test/ → 303 → /login → 200', 'https://os.empresa.test/ → 303 → /login → 200'],
  'ver.hwD': ['GPU, VRAM e runtime registados como detectados; nada sobre rede de computação', 'GPU, VRAM and runtime recorded as detected; nothing about compute networks', 'GPU, VRAM et runtime enregistrés comme détectés ; rien sur les réseaux de calcul'],
  'ver.failT': ['Os serviços correm, mas o Core não está pronto', 'Services are running, but the Core is not ready', 'Les services tournent, mais le Core n’est pas prêt'],
  'ver.failB': ['/ready responde BLOCKED: o componente de compatibilidade diz que o Workspace e o Core falam versões de contrato diferentes. A instalação não está operacional e não é declarada concluída.', '/ready answers BLOCKED: the compatibility component says the Workspace and the Core speak different contract versions. The installation is not operational and is not declared complete.', '/ready répond BLOCKED : le composant de compatibilité indique que le Workspace et le Core parlent des versions de contrat différentes. L’installation n’est pas opérationnelle et n’est pas déclarée terminée.'],
  'ver.failN': ['Verificar novamente pergunta outra vez sem mexer em nada. Se persistir, guarde o relatório: o pacote tem imagens de versões diferentes. A credencial temporária já existe e é mostrada uma vez.', 'Check again asks once more without changing anything. If it persists, save the report: the package contains images of different versions. The temporary credential already exists and is shown once.', 'Vérifier à nouveau interroge encore sans rien modifier. Si cela persiste, enregistrez le rapport : le paquet contient des images de versions différentes. L’identifiant temporaire existe déjà et est affiché une fois.'],
  'ver.blocked': ['BLOCKED · incompatível', 'BLOCKED · incompatible', 'BLOCKED · incompatible'],

  // ── I16 concluído
  'done.title': ["Ocinye OS operacional","Ocinye OS operational","Ocinye OS opérationnel"],
  'done.lead': ["Instalação concluída, endereços e certificado verificados a partir deste computador. Abra o Ocinye OS e entre com a credencial temporária.","Installation complete, addresses and certificate verified from this computer. Open Ocinye OS and sign in with the temporary credential.","Installation terminée, adresses et certificat vérifiés depuis cet ordinateur. Ouvrez Ocinye OS et connectez-vous avec l’identifiant temporaire."],
  'done.ok': ['Instalação verificada', 'Installation verified', 'Installation vérifiée'],
  'done.okD': ['{n} de {n} verificações · {t}', '{n} of {n} checks · {t}', '{n} sur {n} vérifications · {t}'],
  'done.pendT': ["Configuração externa pendente","External configuration pending","Configuration externe en attente"],
  'done.pendD': ["A instalação está concluída e verificada no servidor. {h} ainda não resolve para {ip}: o Ocinye OS não está operacional neste endereço e «Abrir Ocinye OS» fica desactivado até o DNS estar correcto.","Installation is complete and verified on the server. {h} does not resolve to {ip} yet: Ocinye OS is not operational at this address and “Open Ocinye OS” stays disabled until DNS is correct.","L’installation est terminée et vérifiée sur le serveur. {h} ne résout pas encore vers {ip} : Ocinye OS n’est pas opérationnel à cette adresse et « Ouvrir Ocinye OS » reste désactivé jusqu’à ce que le DNS soit correct."],
  'done.instance': ['Instância', 'Instance', 'Instance'],
  'done.server': ['Servidor', 'Server', 'Serveur'],
  'done.release': ['Release', 'Release', 'Version'],
  'done.hw': ['Hardware detectado', 'Detected hardware', 'Matériel détecté'],
  'done.dists': ['Distribuições', 'Distributions', 'Distributions'],
  'done.eps': ['Pontos de acesso', 'Access endpoints', 'Points d’accès'],
  'done.next': ['A seguir', 'Next', 'Ensuite'],
  'done.next1': ['Entre em https://os.empresa.test com a identidade privilegiada; defina a palavra-passe e o segundo factor.', 'Sign in at https://os.empresa.test with the privileged identity; set the password and second factor.', 'Connectez-vous sur https://os.empresa.test avec l’identité privilégiée ; définissez le mot de passe et le second facteur.'],
  'done.next2': ['Guarde a raiz de selagem (/etc/ocinye/core.env) fora do servidor.', 'Keep the sealing root (/etc/ocinye/core.env) off the server.', 'Conservez la racine de scellement (/etc/ocinye/core.env) hors du serveur.'],
  'done.next3': ['Dê acesso aos membros em Administração.', 'Give members access in Administration.', 'Donnez l’accès aux membres dans Administration.'],
  'done.opens': ['Abre no browser deste computador.', 'Opens in this computer’s browser.', 'S’ouvre dans le navigateur de cet ordinateur.'],

  // ── I17 credencial
  'cred.title': ['Credencial temporária', 'Temporary credential', 'Identifiant temporaire'],
  'cred.lead': ['Mostrada uma única vez. Não fica no relatório, no diário, nos registos nem neste computador.', 'Shown only once. It is not kept in the report, the journal, the logs or on this computer.', 'Affiché une seule fois. Il n’est conservé ni dans le rapport, ni dans le journal, ni dans les journaux, ni sur cet ordinateur.'],
  'cred.user': ['Utilizador', 'User', 'Utilisateur'],
  'cred.valid': ['Válida até', 'Valid until', 'Valable jusqu’au'],
  'cred.secret': ['Palavra-passe temporária', 'Temporary password', 'Mot de passe temporaire'],
  'cred.placeholder': ['EXEMPLO-FICTICIO-0000', 'FAKE-EXAMPLE-0000', 'EXEMPLE-FICTIF-0000'],
  'cred.after': ['Ao fechar este passo, a credencial é apagada da memória do instalador. Se a perder antes do primeiro acesso, siga o runbook de recuperação de acesso administrativo.', 'When you close this step, the credential is erased from the installer’s memory. If you lose it before first access, follow the administrative access recovery runbook.', 'En fermant cette étape, l’identifiant est effacé de la mémoire de l’installateur. Si vous le perdez avant le premier accès, suivez le runbook de récupération de l’accès administratif.'],
  'cred.clip': ['Copiar põe-na na área de transferência durante 60 s.', 'Copy places it on the clipboard for 60 s.', 'Copier la place dans le presse-papiers pendant 60 s.'],

  // ── I18 relatório
  'rcp.title': ['Relatório de instalação', 'Installation report', 'Rapport d’installation'],
  'rcp.lead': ['Um registo sem segredos do que foi instalado e verificado. Guarda-se em JSON (para máquinas) e lê-se aqui.', 'A secret-free record of what was installed and verified. Saved as JSON (for machines) and read here.', 'Un enregistrement sans secrets de ce qui a été installé et vérifié. Enregistré en JSON (pour les machines) et lisible ici.'],
  'rcp.id': ['Instalação', 'Installation', 'Installation'],
  'rcp.hostKey': ['Chave do servidor', 'Server key', 'Clé du serveur'],
  'rcp.started': ['Início', 'Started', 'Début'],
  'rcp.ended': ['Fim', 'Ended', 'Fin'],
  'rcp.artifacts': ['Artefactos (SHA-256)', 'Artifacts (SHA-256)', 'Artefacts (SHA-256)'],
  'rcp.verification': ['Verificação', 'Verification', 'Vérification'],
  'rcp.never': ['Nunca neste relatório', 'Never in this report', 'Jamais dans ce rapport'],
  'rcp.neverV': ['palavras-passe, credencial temporária, chaves privadas SSH ou TLS, credenciais da base, segredos de sessão, raiz de selagem, ganhos ou contas de pagamento, localização precisa', 'passwords, temporary credential, SSH or TLS private keys, database credentials, session secrets, sealing root, earnings or payment accounts, precise location', 'mots de passe, identifiant temporaire, clés privées SSH ou TLS, identifiants de base, secrets de session, racine de scellement, gains ou comptes de paiement, localisation précise'],
  'rcp.file': ['Ficheiro', 'File', 'Fichier'],

  // ── comuns
  'c.yes': ['sim', 'yes', 'oui'],
  'c.no': ['não', 'no', 'non'],
  'c.example': ['valores de exemplo', 'example values', 'valeurs d’exemple'],
  'c.ready': ['READY', 'READY', 'READY'],
  'c.tlsSelf': ['auto-assinado · teste', 'self-signed · test', 'auto-signé · test'],
  'c.tlsProvided': ['fornecido · válido até 2027-09-30', 'provided · valid until 2027-09-30', 'fourni · valable jusqu’au 2027-09-30'],
  'c.nogpu': ['sem GPU', 'no GPU', 'sans GPU'],
  'c.localTime': ['hora local', 'local time', 'heure locale'],
  'st.willInstall': ["SERÁ INSTALADO","WILL BE INSTALLED","SERA INSTALLÉ"],
  'st.willApply': ["SERÁ APLICADO","WILL BE APPLIED","SERA APPLIQUÉ"],
  'st.external': ["ACÇÃO EXTERNA","EXTERNAL ACTION","ACTION EXTERNE"],
  'pre.dockerInstall': ["Não instalado · o plano vai instalar Docker Engine e o plugin compose a partir do repositório oficial do Docker para Debian 12. Nada é instalado nesta verificação.","Not installed · the plan will install Docker Engine and the compose plugin from Docker’s official repository for Debian 12. Nothing is installed by this check.","Non installé · le plan installera Docker Engine et le plugin compose depuis le dépôt officiel de Docker pour Debian 12. Rien n’est installé par cette vérification."],
  'pre.dockerConflict': ["Encontrado podman-docker a fornecer o comando docker. O instalador não substitui um runtime de contentores existente: remova-o ou use outro servidor.","Found podman-docker providing the docker command. The installer does not replace an existing container runtime: remove it or use another server.","podman-docker trouvé fournissant la commande docker. L’installateur ne remplace pas un runtime de conteneurs existant : retirez-le ou utilisez un autre serveur."],
  'pre.runtimeT': ["Docker vai ser instalado pelo instalador","Docker will be installed by the installer","Docker sera installé par l’installateur"],
  'pre.runtimeB': ["O servidor é suportado e o Docker falta. Fica no plano de instalação como alteração explícita; só acontece depois de confirmar «Instalar Ocinye OS».","The server is supported and Docker is missing. It goes into the installation plan as an explicit change; it only happens after you confirm “Install Ocinye OS”.","Le serveur est pris en charge et Docker manque. Il figure dans le plan d’installation comme modification explicite ; cela n’a lieu qu’après confirmation de « Installer Ocinye OS »."],
  'pre.fw': ["Firewall do sistema","System firewall","Pare-feu du système"],
  'pre.fwUfw': ["ufw activo · as regras 80/tcp e 443/tcp do Ocinye vão ser acrescentadas, com o comentário «ocinye». As outras regras não mudam.","ufw active · Ocinye rules 80/tcp and 443/tcp will be added, commented “ocinye”. Other rules are unchanged.","ufw actif · les règles Ocinye 80/tcp et 443/tcp seront ajoutées, avec le commentaire « ocinye ». Les autres règles ne changent pas."],
  'pre.fwNone': ["Nenhuma firewall do sistema activa neste servidor","No active system firewall on this server","Aucun pare-feu système actif sur ce serveur"],
  'pre.fwCustom': ["Regras nftables próprias neste servidor. O instalador não as altera: é precisa uma acção externa para 80/tcp e 443/tcp.","Custom nftables rules on this server. The installer does not change them: an external action is needed for 80/tcp and 443/tcp.","Règles nftables personnalisées sur ce serveur. L’installateur ne les modifie pas : une action externe est requise pour 80/tcp et 443/tcp."],
  'pre.fwExtT': ["Acção externa na firewall","External firewall action","Action externe sur le pare-feu"],
  'pre.fwExtB': ["Pode instalar. Para as pessoas chegarem ao Ocinye OS, a firewall deste servidor (ou do fornecedor) tem de aceitar ligações de entrada TCP nas portas 80 e 443, de qualquer origem, para {ip}. Enquanto não aceitar, a instalação fica com activação pendente.","You can install. For people to reach Ocinye OS, this server’s (or the provider’s) firewall must accept inbound TCP on ports 80 and 443, from any source, to {ip}. Until it does, the installation stays activation-pending.","Vous pouvez installer. Pour que les personnes atteignent Ocinye OS, le pare-feu de ce serveur (ou du fournisseur) doit accepter les connexions TCP entrantes sur les ports 80 et 443, de toute origine, vers {ip}. Tant que ce n’est pas le cas, l’installation reste en activation en attente."],
  'pre.fwTh': ["PORTA · PROTOCOLO · SENTIDO · RAZÃO","PORT · PROTOCOL · DIRECTION · REASON","PORT · PROTOCOLE · SENS · RAISON"],
  'pre.fw80': ["80/tcp · entrada · redirecciona para HTTPS","80/tcp · inbound · redirects to HTTPS","80/tcp · entrant · redirige vers HTTPS"],
  'pre.fw443': ["443/tcp · entrada · Workspace em HTTPS","443/tcp · inbound · Workspace over HTTPS","443/tcp · entrant · Workspace en HTTPS"],
  'rev.chPrereq': ["Instala Docker Engine e o plugin compose (docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin) do repositório oficial do Docker para Debian 12, com a chave do repositório verificada pela impressão digital do manifesto. Necessário: o Ocinye OS corre em contentores. Não havia runtime de contentores neste servidor.","Installs Docker Engine and the compose plugin (docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin) from Docker’s official Debian 12 repository, with the repository key checked against the manifest fingerprint. Required: Ocinye OS runs in containers. There was no container runtime on this server.","Installe Docker Engine et le plugin compose (docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin) depuis le dépôt officiel Docker pour Debian 12, avec la clé du dépôt vérifiée par l’empreinte du manifeste. Requis : Ocinye OS s’exécute en conteneurs. Il n’y avait pas de runtime de conteneurs sur ce serveur."],
  'rev.chFw': ["Acrescenta ao ufw: allow 80/tcp e allow 443/tcp, com o comentário «ocinye». Não remove nem altera outras regras; a porta SSH fica como está.","Adds to ufw: allow 80/tcp and allow 443/tcp, commented “ocinye”. Does not remove or change other rules; the SSH port is left as is.","Ajoute à ufw : allow 80/tcp et allow 443/tcp, avec le commentaire « ocinye ». Ne retire ni ne modifie d’autres règles ; le port SSH reste inchangé."],
  'rev.prereq': ["Pré-requisitos","Prerequisites","Prérequis"],
  'ph.P15': ["Verificar o produto","Verify the product","Vérifier le produit"],
  'ph.P16': ["Remover o executor temporário","Remove the temporary executor","Supprimer l’exécuteur temporaire"],
  'op.P04': ["docker-ce 27.x · docker-compose-plugin · serviço docker activo","docker-ce 27.x · docker-compose-plugin · docker service active","docker-ce 27.x · docker-compose-plugin · service docker actif"],
  'fail.preT': ["P04 · a instalação do Docker falhou","P04 · Docker installation failed","P04 · l’installation de Docker a échoué"],
  'fail.preR': ["O repositório do Docker respondeu 503 durante a transferência de docker-ce. Nenhum pacote ficou meio instalado: o apt reverteu a transacção.","Docker’s repository answered 503 while fetching docker-ce. No package was left half-installed: apt rolled the transaction back.","Le dépôt Docker a répondu 503 lors du téléchargement de docker-ce. Aucun paquet n’est resté à moitié installé : apt a annulé la transaction."],
  'fail.preN': ["Repetível: tente novamente; a verificação prévia já confirmou o acesso de saída. Nada do Ocinye foi escrito ainda.","Retryable: try again; the preflight already confirmed outbound access. Nothing of Ocinye has been written yet.","Répétable : réessayez ; la vérification préalable a déjà confirmé l’accès sortant. Rien d’Ocinye n’a encore été écrit."],
  'lc.install': ["INSTALAÇÃO","INSTALLATION","INSTALLATION"],
  'lc.activation': ["ACTIVAÇÃO","ACTIVATION","ACTIVATION"],
  'lc.operational': ["OPERACIONAL","OPERATIONAL","OPÉRATIONNEL"],
  'lc.complete': ["CONCLUÍDA","COMPLETE","TERMINÉE"],
  'lc.pendingDns': ["PENDENTE · DNS","PENDING · DNS","EN ATTENTE · DNS"],
  'lc.testMode': ["MODO DE TESTE","TEST MODE","MODE TEST"],
  'lc.yes': ["SIM","YES","OUI"],
  'lc.no': ["NÃO","NO","NON"],
  'done.titleInstalled': ["Ocinye OS instalado","Ocinye OS installed","Ocinye OS installé"],
  'done.recheckNote': ["Quando o DNS estiver correcto, «Verificar novamente» repete as verificações de endereço e certificado.","When DNS is correct, “Check again” reruns the address and certificate checks.","Quand le DNS sera correct, « Vérifier à nouveau » relance les vérifications d’adresse et de certificat."],
  'done.titleTest': ["Ocinye OS instalado · modo de teste","Ocinye OS installed · test mode","Ocinye OS installé · mode test"],
  'done.testT': ["Instalação de teste concluída","Test installation complete","Installation de test terminée"],
  'done.testD': ["Verificado com o certificado auto-assinado. Serve laboratório e desenvolvimento; não é uma instalação operacional para uso público. Os browsers mostram um aviso ao abrir.","Verified with the self-signed certificate. Fit for lab and development; it is not an operational installation for public use. Browsers show a warning when opening.","Vérifiée avec le certificat auto-signé. Convient au laboratoire et au développement ; ce n’est pas une installation opérationnelle pour un usage public. Les navigateurs affichent un avertissement à l’ouverture."],
  'done.openTest': ["Abrir em modo de teste","Open in test mode","Ouvrir en mode test"],
  'ver.fw': ["Portas 80 e 443 alcançáveis","Ports 80 and 443 reachable","Ports 80 et 443 joignables"],
  'ver.fwD': ["Ligação TCP a partir deste computador","TCP connection from this computer","Connexion TCP depuis cet ordinateur"]
};
