#!/usr/bin/env python3
"""Todo o commit tem uma identidade humana permitida.

# Porque isto existe

O `CLAUDE.md` §72 diz que os commits pertencem exclusivamente aos autores
humanos. Isso esteve escrito como norma e não como portão, e duas identidades
entraram na mesma: um endereço de outra organização, em três commits, e um bot
de actualização de dependências, em seis.

Nenhuma delas foi maliciosa. Uma foi um `git config` esquecido; a outra foi o
GitHub a fazer o que lhe pediram. Ambas se tornaram permanentes assim que foram
publicadas, porque uma referência de Pull Request guarda o commit para sempre e
não se apaga por push — o que obrigou, para as retirar, a recriar o repositório.

Um portão custa uma execução. Recriar o repositório custou vinte Pull Requests,
o histórico de CI e a data de criação.

# O que se permite, e porquê

As duas identidades que resolvem para a mesma conta humana. O `noreply` do
GitHub está incluído porque um merge feito pela interface web usa-o, e recusá-lo
faria a CI reprovar merges legítimos.

# Clonagem rasa

Se a árvore só tem parte da história, isto diz-o e falha. Um portão que percorre
um commit e reporta verde é pior do que não existir: afirma uma propriedade
sobre a história inteira tendo observado uma fatia.

Offline. Só lê.
"""
import subprocess
import sys

# Autor: quem escreveu. É o que a lista de contribuidores do GitHub conta, e é
# aqui que a regra tem de ser estreita.
AUTORES = {
    "fidelrmonteiro@gmail.com",
    "56933720+fm65@users.noreply.github.com",
}

# Committer: quem aplicou. Um merge feito pela interface do GitHub tem
# `GitHub <noreply@github.com>` como committer e a pessoa como autor — recusá-lo
# faria a CI reprovar merges legítimos, e não muda quem consta como contribuidor.
COMMITTERS = AUTORES | {"noreply@github.com"}

# Marcas de atribuição a máquinas, proibidas pelo `CLAUDE.md` §72.
#
# A regra existe desde o primeiro dia e nunca teve portão. Está aqui porque uma
# norma que ninguém mede é uma norma que se descobre violada quando já é
# permanente.
TRAILERS = (
    "co-authored-by: claude",
    "generated with claude",
    "generated by claude",
    "ai-generated",
    "ai-assisted commit",
)


def git(*args):
    return subprocess.run(
        ["git", *args], capture_output=True, text=True, check=True
    ).stdout


def main():
    raso = git("rev-parse", "--is-shallow-repository").strip() == "true"

    linhas = [
        linha
        for linha in git(
            "log", "--all", "--format=%H%x1f%ae%x1f%ce%x1f%s"
        ).splitlines()
        if linha
    ]

    intrusos = []
    for linha in linhas:
        sha, autor, committer, assunto = linha.split("\x1f", 3)
        if autor not in AUTORES:
            intrusos.append(f"{sha[:9]} autor «{autor}» — {assunto[:56]}")
        if committer not in COMMITTERS:
            intrusos.append(f"{sha[:9]} committer «{committer}» — {assunto[:56]}")

    # E nenhuma mensagem atribui autoria a uma máquina.
    corpos = git("log", "--all", "--format=%H%x1f%B%x1e").split("\x1e")
    for bloco in corpos:
        bloco = bloco.strip()
        if not bloco:
            continue
        sha, _, corpo = bloco.partition("\x1f")
        baixo = corpo.lower()
        for marca in TRAILERS:
            if marca in baixo:
                intrusos.append(f"{sha[:9]} mensagem contém «{marca}»")

    if intrusos:
        print("Identidades não permitidas na história:", file=sys.stderr)
        for intruso in intrusos:
            print(f"  {intruso}", file=sys.stderr)
        print(file=sys.stderr)
        print("  Autores permitidos:", ", ".join(sorted(AUTORES)), file=sys.stderr)
        print(
            "  Um commit publicado com outra identidade não se retira sem "
            "recriar o repositório.",
            file=sys.stderr,
        )
        return 1

    if raso:
        print(
            "A clonagem é rasa: este portão observou "
            f"{len(linhas)} commit(s) e não a história inteira.",
            file=sys.stderr,
        )
        print(
            "  Correr com `fetch-depth: 0`, ou o verde não afirma nada.",
            file=sys.stderr,
        )
        return 1

    print(
        f"Autoria: {len(linhas)} commits, todos com identidade permitida "
        "e sem atribuição a máquinas"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
